### ISSUE TITLE
Is there any way to solve this problem?

### ISSUE THREAD

**Issue by JJSEONG** [ProjectOpenSea/opensea-js#1097]
This code worked fine when using v5.
After using v6, the following error occurs.
Can anyone let me know if anyone has encountered this error or solved it?

- My Code
```
try {
      const expirationTime = Math.round(Date.now() / 1000 + 60 * 60 * 24 * 90);
      console.log('getSeaport()', await getSeaport());
      const listing = await getSeaport().createSellOrder({
        asset: {
          tokenId,
          tokenAddress: REACT_APP_ETHEREUM_MINTING_CONTRACT_ADDRESS,
        },
        accountAddress: account,
        startAmount: price,
        endAmount: price,
        expirationTime,
      });
      setTxHash(listing);
      setTxLoading(false);
    } catch (e) {
      console.error(e);
      toastError('Listing failed', 'Please try again');
      resetTxHash();
      setTxLoading(false);
    }
```

- Error
**vendors~main.chunk.js:111276 Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":49,\"error\":{\"code\":-32601,\"message\":\"The method eth_signTypedData_v4 does not exist/is not available\"}}", error={"code":-32601}, requestBody="{\"method\":\"eth_signTypedData_v4\",\"params\":[\"0xc0751b9054be33caae11d415281cac9591ad3ef8\",\"{\\\"types\\\":{\\\"OrderComponents\\\":[{\\\"name\\\":\\\"offerer\\\",\\\"type\\\":\\\"address\\\"},{\\\"name\\\":\\\"zone\\\",\\\"type\\\":\\\"address\\\"},{\\\"name\\\":\\\"offer\\\",\\\"type\\\":\\\"OfferItem[]\\\"},{\\\"name\\\":\\\"consideration\\\",\\\"type\\\":\\\"ConsiderationItem[]\\\"},{\\\"name\\\":\\\"orderType\\\",\\\"type\\\":\\\"uint8\\\"},{\\\"name\\\":\\\"startTime\\\",\\\"type\\\":\\\"uint256\\\"},{\\\"name\\\":\\\"endTime\\\",\\\"type\\\":\\\"uint256\\\"},{\\\"name\\\":\\\"zoneHash\\\",\\\"type\\\":\\\"bytes32\\\"},{\\\"name\\\":\\\"salt\\\",\\\"type\\\":\\\"uint256\\\"},{\\\"name\\\":\\\"conduitKey\\\",\\\"type\\\":\\\"bytes32\\\"},{\\\"name\\\":\\\"counter\\\",\\\"type\\\":\\\"uint256\\\"}],\\\"OfferItem\\\":[{\\\"name\\\":\\\"itemType\\\",\\\"type\\\":\\\"uint8\\\"},{\\\"name\\\":\\\"token\\\",\\\"type\\\":\\\"address\\\"},{\\\"name\\\":\\\"identifierOrCriteria\\\",\\\"type\\\":\\\"uint256\\\"},{\\\"name\\\":\\\"startAmount\\\",\\\"type\\\":\\\"uint256\\\"},{\\\"name\\\":\\\"endAmount\\\",\\\"type\\\":\\\"uint256\\\"}],\\\"ConsiderationItem\\\":[{\\\"name\\\":\\\"itemType\\\",\\\"type\\\":\\\"uint8\\\"},{\\\"name\\\":\\\"token\\\",\\\"type\\\":\\\"address\\\"},{\\\"name\\\":\\\"identifierOrCriteria\\\",\\\"type\\\":\\\"uint256\\\"},{\\\"name\\\":\\\"startAmount\\\",\\\"type\\\":\\\"uint256\\\"},{\\\"name\\\":\\\"endAmount\\\",\\\"type\\\":\\\"uint256\\\"},{\\\"name\\\":\\\"recipient\\\",\\\"type\\\":\\\"address\\\"}],\\\"EIP712Domain\\\":[{\\\"name\\\":\\\"name\\\",\\\"type\\\":\\\"string\\\"},{\\\"name\\\":\\\"version\\\",\\\"type\\\":\\\"string\\\"},{\\\"name\\\":\\\"chainId\\\",\\\"type\\\":\\\"uint256\\\"},{\\\"name\\\":\\\"verifyingContract\\\",\\\"type\\\":\\\"address\\\"}]},\\\"domain\\\":{\\\"name\\\":\\\"Seaport\\\",\\\"version\\\":\\\"1.5\\\",\\\"chainId\\\":\\\"5\\\",\\\"verifyingContract\\\":\\\"0x00000000000000adc04c56bf30ac9d3c0aaf14dc\\\"},\\\"primaryType\\\":\\\"OrderComponents\\\",\\\"message\\\":{\\\"offerer\\\":\\\"0xc0751b9054be33caae11d415281cac9591ad3ef8\\\",\\\"zone\\\":\\\"0x0000000000000000000000000000000000000000\\\",\\\"offer\\\":[{\\\"itemType\\\":\\\"2\\\",\\\"token\\\":\\\"0x97911390baef999af13ea7fa0bf60dbaa1362ec7\\\",\\\"identifierOrCriteria\\\":\\\"45\\\",\\\"startAmount\\\":\\\"1\\\",\\\"endAmount\\\":\\\"1\\\"}],\\\"consideration\\\":[{\\\"itemType\\\":\\\"0\\\",\\\"token\\\":\\\"0x0000000000000000000000000000000000000000\\\",\\\"identifierOrCriteria\\\":\\\"0\\\",\\\"startAmount\\\":\\\"975000000000000000\\\",\\\"endAmount\\\":\\\"975000000000000000\\\",\\\"recipient\\\":\\\"0xc0751b9054be33caae11d415281cac9591ad3ef8\\\"},{\\\"itemType\\\":\\\"0\\\",\\\"token\\\":\\\"0x0000000000000000000000000000000000000000\\\",\\\"identifierOrCriteria\\\":\\\"0\\\",\\\"startAmount\\\":\\\"25000000000000000\\\",\\\"endAmount\\\":\\\"25000000000000000\\\",\\\"recipient\\\":\\\"0x0000a26b00c1f0df003000390027140000faa719\\\"}],\\\"orderType\\\":\\\"1\\\",\\\"startTime\\\":\\\"1689568299\\\",\\\"endTime\\\":\\\"1697344298\\\",\\\"zoneHash\\\":\\\"0x0000000000000000000000000000000000000000000000000000000000000000\\\",\\\"salt\\\":\\\"0\\\",\\\"conduitKey\\\":\\\"0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000\\\",\\\"counter\\\":\\\"0\\\"}}\"],\"id\":49,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161", code=SERVER_ERROR, version=web/5.7.1)
    at Logger.makeError (vendors~main.chunk.js:12570:19)
    at Logger.throwError (vendors~main.chunk.js:12581:18)
    at _callee$ (vendors~main.chunk.js:28748:20)
    at tryCatch (vendors~main.chunk.js:2255:17)
    at Generator.<anonymous> (vendors~main.chunk.js:2336:22)
    at Generator.next (vendors~main.chunk.js:2280:21)
    at fulfilled (vendors~main.chunk.js:28410:24)**

**Comment by ryanio** [comment]
You likely haven't passed a wallet to the 4th constructor param of the sdk

**Comment by JJSEONG** [comment]
> You likely haven't passed a wallet to the 4th constructor param of the sdk

Thank you for answer. May I know the 4th param you mentioned? Or could you give a full example?

**Comment by JJSEONG** [comment]
> You likely haven't passed a wallet to the 4th constructor param of the sdk

I encountered a new error.
This code was used in v5, and I am using it as it is in read me, but I don't know why the error occurs after updating to v6.
I want to run it in v5, but I updated it to v6 after seeing that it needs to be updated to v6 due to the url_1.URLSearchParams is not a constructor error.

Error
- MetaMask - RPC Error: execution reverted: ERC721Burnable: caller is not owner nor approved
- Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="ownerOf(uint256)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
- Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="isApprovedForAll(address,address)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)

**Comment by thenerdassassin** [comment]
The integration tests have a good example of initialization: https://github.com/ProjectOpenSea/opensea-js/blob/main/test/integration/setup.ts

**Comment by JJSEONG** [comment]
> The integration tests have a good example of initialization: https://github.com/ProjectOpenSea/opensea-js/blob/main/test/integration/setup.ts

Thank you for your reply. However, the same error occurs even if I use the method you suggested..🥹
