### ISSUE TITLE
Getting error when only trying to import OpenSeaSDK library

### ISSUE THREAD

**Issue by co2nut** [ProjectOpenSea/opensea-js#1171]
### Component

Utils

### Have you ensured that all of these are up to date?

- [X] opensea-js
- [X] Node (minimum v16)

### What version of opensea-js are you on?

6.1.9

### What function is the bug in?

import

### Operating System

macOS (Intel)

### Describe the bug

Getting error below when trying to import the library:

Appreciate if someone could assist on this.

`TypeError: Cannot destructure property 'defineReadOnly' of 'ethers.utils' as it is undefined.
    at Object.<anonymous> (/APPPATH/opensea-api/node_modules/@0xsequence/utils/dist/0xsequence-utils.cjs.dev.js:242:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/APPPATH/opensea-api/node_modules/@0xsequence/utils/dist/0xsequence-utils.cjs.js:6:20)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)`

**Comment by ryanio** [comment]
We don't use @0xsequence in this repository so it must be coming from something else you are importing or using rather than opensea-js. Make sure you are also using ethers v5 with opensea-js

**Comment by StevenJ59** [comment]
> We don't use @0xsequence in this repository so it must be coming from something else you are importing or using rather than opensea-js. Make sure you are also using ethers v5 with opensea-js

I had the same issue by following the quick start here : 
https://github.com/ProjectOpenSea/opensea-js/blob/main/developerDocs/quick-start.md


`import { ethers } from "ethers";
import { OpenSeaSDK, Chain } from "opensea-js";

// This example provider won't let you make transactions, only read-only calls:
const provider = new ethers.providers.JsonRpcProvider(
  "https://mainnet.infura.io",
);

const openseaSDK = new OpenSeaSDK(provider, {
  chain: Chain.Mainnet,
  apiKey: YOUR_API_KEY,
});`


it is not specified anywhere that you need the v5 of ethers, so thank you for your clarifications
