### ISSUE TITLE
Help: when i use createCollectionOffer to create a collection offers

### ISSUE THREAD

**Issue by jokereven** [ProjectOpenSea/opensea-js#1172]
`import { ethers } from "ethers";
import { Chain, OpenSeaSDK } from "opensea-js";

const provider = new ethers.providers.JsonRpcProvider(
    "https://goerli.infura.io/v3/bb7f1a94a0174cac8c6d966fd925dbaa",
);

const openseaSDK = new OpenSeaSDK(provider, {
    chain: Chain.Goerli,
    apiKey: 'MyApiKey'
});

const offer = await openseaSDK.createCollectionOffer({
    collectionSlug: 'azukigoerli',
    accountAddress: 'MyWalletAddress',
    amount: 0.01,
    quantity: 30,
    expirationTime: 3600,
})
`

when i run the code i get `➜  office node main.js
/root/Desktop/github/jokereven/$/office/node_modules/opensea-js/lib/sdk.js:702
            throw new Error(`Specified accountAddress is not available through wallet or provider: ${accountAddressChecksummed}`);
                  ^

Error: Specified accountAddress is not available through wallet or provider: 0xce4BA677aEBcBB178376228801Ac62Bc9Bea6c21
    at OpenSeaSDK.<anonymous> (/root/Desktop/github/jokereven/$/office/node_modules/opensea-js/lib/sdk.js:702:19)
    at Generator.next (<anonymous>)
    at fulfilled (/root/Desktop/github/jokereven/$/office/node_modules/opensea-js/lib/sdk.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0
➜  office ` have some example here

**Comment by jokereven** [comment]
`const offer = await openseaSDK.createCollectionOffer({
        collectionSlug: "azukigoerli",
        accountAddress: web3.utils.toChecksumAddress("0xce4BA677aEBcBB178376228801Ac62Bc9Bea6c21"),
        amount: 0.0001,
        expirationTime: 0,
    });` i have use web3.utils.toChecksumAddress but also get some `/root/Desktop/github/jokereven/$/office/node_modules/opensea-js/lib/sdk.js:702
            throw new Error(`Specified accountAddress is not available through wallet or provider: ${accountAddressChecksummed}`);
                  ^

Error: Specified accountAddress is not available through wallet or provider: 0xce4BA677aEBcBB178376228801Ac62Bc9Bea6c21
    at OpenSeaSDK.<anonymous> (/root/Desktop/github/jokereven/$/office/node_modules/opensea-js/lib/sdk.js:702:19)
    at Generator.next (<anonymous>)
    at fulfilled (/root/Desktop/github/jokereven/$/office/node_modules/opensea-js/lib/sdk.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0`

**Comment by jokereven** [comment]
i have try to use that code https://github.com/ProjectOpenSea/opensea-js/issues/887#issuecomment-1576224762 but get `root/Desktop/github/jokereven/$/office/opensea-trading-sample/node_modules/@ethersproject/logger/lib/index.js:238
        var error = new Error(message);
                    ^

Error: invalid address (argument="address", value={}, code=INVALID_ARGUMENT, version=address/5.7.0)
    at Logger.makeError (/root/Desktop/github/jokereven/$/office/opensea-trading-sample/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/root/Desktop/github/jokereven/$/office/opensea-trading-sample/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/root/Desktop/github/jokereven/$/office/opensea-trading-sample/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at Object.getAddress (/root/Desktop/github/jokereven/$/office/opensea-trading-sample/node_modules/@ethersproject/address/lib/index.js:70:16)
    at OpenSeaSDK.<anonymous> (/root/Desktop/github/jokereven/$/office/opensea-trading-sample/node_modules/opensea-js/lib/sdk.js:695:69)
    at Generator.next (<anonymous>)
    at /root/Desktop/github/jokereven/$/office/opensea-trading-sample/node_modules/opensea-js/lib/sdk.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/root/Desktop/github/jokereven/$/office/opensea-trading-sample/node_modules/opensea-js/lib/sdk.js:4:12)
    at OpenSeaSDK._requireAccountIsAvailable (/root/Desktop/github/jokereven/$/office/opensea-trading-sample/node_modules/opensea-js/lib/sdk.js:694:16) {
  reason: 'invalid address',
  code: 'INVALID_ARGUMENT',
  argument: 'address',
  value: Promise { '0xce4BA677aEBcBB178376228801Ac62Bc9Bea6c21' }
}

Node.js v18.16.0`

**Comment by jokereven** [comment]
and i don't understand https://github.com/ProjectOpenSea/opensea-js/issues/887#issuecomment-1583726951

**Comment by jokereven** [comment]
`const { ethers } = require("ethers");
const { OpenSeaSDK, Chain } = require("opensea-js");

const RPC_URL = `https://eth-mainnet.g.alchemy.com/v2/${APIKEY}`;
const CHAIN = Chain.Mainnet;
const PRIVATE_KEY = `${PRIVATE_KEY}`;

const provider = new ethers.providers.JsonRpcProvider(RPC_URL);
const signer = new ethers.Wallet(PRIVATE_KEY, provider);

const openseaSDK = new OpenSeaSDK(
    provider,
    {
        chain: CHAIN,
        apiKey: `${OPENSEA_API_KEY}`
    },
    undefined,
    signer
);


async function createCollectionOffer(amount) {
    const expirationTime = Math.round(Date.now() / 1000 + 60 * 60 * 24)
    const order = await openseaSDK.createCollectionOffer({
        collectionSlug: 'cryptopunks',
        accountAddress: `${WALLET_ADDRESS}`,
        amount: amount,
        quantity: 30,
        expirationTimeL: expirationTime
    })

    return order;
}

createCollectionOffer(0.1)
`

**Comment by jokereven** [comment]
thanks
