### ISSUE TITLE
OpenSeaAPI.postOrder doesn't properly handle response errors

### ISSUE THREAD

**Issue by lomboreb** [ProjectOpenSea/opensea-js#1321]
### Component

API

### Have you ensured that all of these are up to date?

- [X] opensea-js
- [X] Node (minimum v16)

### What version of opensea-js are you on?

7.0.1

### What function is the bug in?

OpenSeaAPI.postOrder

### Operating System

Windows

### Describe the bug

In OpenSeaAPI.postOrder function, if the POST request is returning an error (e.g. Outstanding order to wallet balance ratio exceeds allowed limit), the deserializeOrder funcion is invoked passing an undefined order and causing the following exception to be raised:

TypeError: Cannot read properties of undefined (reading 'created_date') 
at deserializeOrder (opensea-js\node_modules\opensea-js\lib\orders\utils.js:83:28) 
at OpenSeaAPI.postOrder (opensea-js\lib\api\api.js:181:45)

**Comment by lomboreb** [comment]
all errors causing order to be undefined, should be handled before invoking deserializeOrder function

**Comment by ryanio** [comment]
Thanks for reporting, will open a PR to fix this morning

**Comment by ryanio** [comment]
This should be fixed in [v7.0.2](https://github.com/ProjectOpenSea/opensea-js/releases/tag/v7.0.2), give it a try and please let me know if it is properly throwing/returning server errors now. Thanks!

**Comment by toufique-imam** [comment]
Not fixed yet @ryanio

**Comment by ryanio** [comment]
> Not fixed yet @ryanio 

Can you please share code to reproduce the issue

**Comment by toufique-imam** [comment]
> > Not fixed yet @ryanio
> 
> Can you please share code to reproduce the issue
```js
        try {
            const nft_params = await getOrder(openseaSDK, tokenId, address, startAmount, endAmount, timePeriod)
            console.log("sellNFT>>nft_params", nft_params)
            const signature = await signOrder(nft_params, address)
            console.log("sellNFT>>signature", signature)
            const order: OrderWithCounter = {
                parameters: nft_params,
                signature: signature
            }
            const res = await openseaSDK.api.postOrder(order, {
                protocol: "seaport",
                protocolAddress: CROSS_CHAIN_SEAPORT_V1_5_ADDRESS,
                side: OrderSide.ASK
            });
            console.log("sellNFT>>Res", res)
            toast.success("NFT listed for sale")
        }
        catch (e) {
            console.log("sellNFT", e)
            toast.error("Error selling NFT")
        }
```
![image](https://github.com/ProjectOpenSea/opensea-js/assets/29049430/2fbb15b5-7e6b-42b1-9167-9f243ab3d5db)
Kind of like this

**Comment by ryanio** [comment]
@toufique-imam thanks I was able to reproduce and found out it was this line, will release shortly https://github.com/ProjectOpenSea/opensea-js/pull/1328

**Comment by ryanio** [comment]
@toufique-imam [v7.0.3](https://github.com/ProjectOpenSea/opensea-js/releases/tag/v7.0.3) is released now with the fix, can you try again?

**Comment by toufique-imam** [comment]
> @toufique-imam [v7.0.3](https://github.com/ProjectOpenSea/opensea-js/releases/tag/v7.0.3) is released now with the fix, can you try again?
Yes previous error isn't coming now
