### ISSUE TITLE
Can't get started on Ubuntu (WSL2) - nothing works - (The requested module does not provide an export named 'OpenSeaPort')

### ISSUE THREAD

**Issue by MaurGi** [ProjectOpenSea/opensea-js#143]
looking at the readme, trying the following with node 8.11 as per [installation instructions](https://github.com/ProjectOpenSea/opensea-js#installation), getting lots of errors, cannot get it going, help?

With 8.11:

```sh
$ nvm use default 8.11
Now using node v8.11.4 (npm v5.6.0)
$ node -v
v8.11.4
$ npm list
/home/maurgi
└── (empty)
$ npm install web3
<multiple warnings>
+ web3@1.5.2
added 366 packages in 41.584s
$ npm install --save opensea-js
<multiple warnings>
+ opensea-js@1.1.13
added 666 packages in 85.732s
```

Saved the [Getting Started](https://github.com/ProjectOpenSea/opensea-js#getting-started) code in testclient.js:

```sh
$ node testclient.js           
/home/maurgi/zed/OpenSea/testclient.js:1
(function (exports, require, module, __filename, __dirname) { import * as Web3 from 'web3';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
``` 

Per [Node.js - SyntaxError: Unexpected token import](https://stackoverflow.com/questions/39436322/node-js-syntaxerror-unexpected-token-import), renamed to `.mjs` then:

```sh
$ node --experimental-modules testclient.mjs
(node:15161) ExperimentalWarning: The ESM module loader is experimental.
SyntaxError: The requested module does not provide an export named 'OpenSeaPort'
    at ModuleJob._instantiate (internal/loader/ModuleJob.js:85:17)
    at <anonymous>
```

Upgrading to node 13:

```sh
$ nvm install 13 
...
Checksums matched!
Now using node v13.14.0 (npm v6.14.4)
$ npm update
$ node testclient.mjs 
file:///home/maurgi/zed/OpenSea/testclient.mjs:2
import { OpenSeaPort, Network } from 'opensea-js'
                      ^^^^^^^
SyntaxError: The requested module 'opensea-js' does not provide an export named 'Network'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

Upgrading to node 15:

```sh
$ nvm install 15 
Now using node v15.14.0 (npm v7.7.6)
$ npm upgrade
...
added 92 packages, removed 74 packages, changed 23 packages, and audited 1051 packages in 53s
...
$ node testclient.mjs
file:///home/maurgi/zed/OpenSea/testclient.mjs:5
const provider = new Web3.providers.HttpProvider('https://mainnet.infura.io')
                                    ^

TypeError: Cannot read property 'HttpProvider' of undefined
    at file:///home/maurgi/zed/OpenSea/testclient.mjs:5:37
    at ModuleJob.run (node:internal/modules/esm/module_job:154:23)
    at async Loader.import (node:internal/modules/esm/loader:177:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
```

Trying to remove and reinstall packages:

```sh
$ npm remove opensea-js
$ npm remove web3
$ npm list
/home/maurgi
└── (empty)
$  node -v
v15.14.0
$ npm install --save opensea-js
npm WARN deprecated safe-event-emitter@1.0.1: Renamed to @metamask/safe-event-emitter
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated ethereumjs-block@2.2.2: New package name format for new versions: @ethereumjs/block. Please update.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated ethereumjs-tx@2.1.2: New package name format for new versions: @ethereumjs/tx. Please update.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated ethereumjs-tx@1.3.7: New package name format for new versions: @ethereumjs/tx. Please update.
npm WARN deprecated bignumber.js@6.0.0: Custom ALPHABET bug fixed in v7.0.2
npm WARN deprecated ethereumjs-vm@2.6.0: New package name format for new versions: @ethereumjs/vm. Please update.
npm WARN deprecated axios@0.17.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated ethereumjs-block@1.7.1: New package name format for new versions: @ethereumjs/block. Please update.
npm WARN deprecated ethereumjs-common@1.5.2: New package name format for new versions: @ethereumjs/common. Please update.
npm WARN deprecated core-js@1.2.7: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /home/maurgi/.nvm/versions/node/v15.14.0/bin/node /home/maurgi/.nvm/versions/node/v15.14.0/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/maurgi/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN deprecated safe-event-emitter@1.0.1: Renamed to @metamask/safe-event-emitter
npm ERR! npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm ERR! npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! npm WARN deprecated ethereumjs-block@2.2.0: New package name format for new versions: @ethereumjs/block. Please update.
npm ERR! npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm ERR! npm WARN deprecated chokidar@2.1.6: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm ERR! npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm ERR! npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm ERR! npm WARN deprecated uuid@3.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm ERR! npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! npm WARN deprecated ethereumjs-tx@1.3.7: New package name format for new versions: @ethereumjs/tx. Please update.
npm ERR! npm WARN deprecated bignumber.js@6.0.0: Custom ALPHABET bug fixed in v7.0.2
npm ERR! npm WARN deprecated ethereumjs-vm@2.6.0: New package name format for new versions: @ethereumjs/vm. Please update.
npm ERR! npm WARN deprecated buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
npm ERR! npm WARN deprecated axios@0.17.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm ERR! npm WARN deprecated ethereumjs-block@1.7.1: New package name format for new versions: @ethereumjs/block. Please update.
npm ERR! npm WARN deprecated ethereumjs-common@1.3.1: New package name format for new versions: @ethereumjs/common. Please update.
npm ERR! npm WARN deprecated core-js@2.6.9: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /home/maurgi/.npm/_cacache/tmp/git-clone-212ef9b3/node_modules/sha3
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c node-gyp rebuild
npm ERR! npm ERR! make: Entering directory '/home/maurgi/.npm/_cacache/tmp/git-clone-212ef9b3/node_modules/sha3/build'
npm ERR! npm ERR!   CXX(target) Release/obj.target/sha3/src/addon.o
npm ERR! npm ERR! make: Leaving directory '/home/maurgi/.npm/_cacache/tmp/git-clone-212ef9b3/node_modules/sha3/build'
npm ERR! npm ERR! gyp info it worked if it ends with ok
npm ERR! npm ERR! gyp info using node-gyp@7.1.2
npm ERR! npm ERR! gyp info using node@15.14.0 | linux | x64
npm ERR! npm ERR! gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
npm ERR! npm ERR! gyp info spawn /usr/bin/python3
npm ERR! npm ERR! gyp info spawn args [
npm ERR! npm ERR! gyp info spawn args   '/home/maurgi/.nvm/versions/node/v15.14.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! npm ERR! gyp info spawn args   '-f',
npm ERR! npm ERR! gyp info spawn args   'make',
npm ERR! npm ERR! gyp info spawn args   '-I',
npm ERR! npm ERR! gyp info spawn args   '/home/maurgi/.npm/_cacache/tmp/git-clone-212ef9b3/node_modules/sha3/build/config.gypi',
npm ERR! npm ERR! gyp info spawn args   '-I',
npm ERR! npm ERR! gyp info spawn args   '/home/maurgi/.nvm/versions/node/v15.14.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! npm ERR! gyp info spawn args   '-I',
npm ERR! npm ERR! gyp info spawn args   '/home/maurgi/.cache/node-gyp/15.14.0/include/node/common.gypi',
npm ERR! npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/maurgi/.cache/node-gyp/15.14.0',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/maurgi/.nvm/versions/node/v15.14.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/maurgi/.cache/node-gyp/15.14.0/<(target_arch)/node.lib',
npm ERR! npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/maurgi/.npm/_cacache/tmp/git-clone-212ef9b3/node_modules/sha3',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! npm ERR! gyp info spawn args   '--depth=.',
npm ERR! npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! npm ERR! gyp info spawn args   '--generator-output',
npm ERR! npm ERR! gyp info spawn args   'build',
npm ERR! npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! npm ERR! gyp info spawn args ]
npm ERR! npm ERR! gyp info spawn make
npm ERR! npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! npm ERR! In file included from ../src/addon.cpp:4:
npm ERR! npm ERR! ../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
npm ERR! npm ERR! ../node_modules/nan/nan.h:2232:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
npm ERR! npm ERR!  2232 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
npm ERR! npm ERR!       |                                                              ^
npm ERR! npm ERR! ../src/addon.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE SHA3Hash::New(Nan::NAN_METHOD_ARGS_TYPE)’:
npm ERR! npm ERR! ../src/addon.cpp:49:23: warning: ‘new’ of type ‘SHA3Hash’ with extended alignment 32 [-Waligned-new=]
npm ERR! npm ERR!    49 |    obj = new SHA3Hash();
npm ERR! npm ERR!       |                       ^
npm ERR! npm ERR! ../src/addon.cpp:49:23: note: uses ‘void* operator new(std::size_t)’, which does not have an alignment parameter
npm ERR! npm ERR! ../src/addon.cpp:49:23: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
npm ERR! npm ERR! ../src/addon.cpp: In static member function ‘static void SHA3Hash::Init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
npm ERR! npm ERR! ../src/addon.cpp:83:27: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>&, v8::Local<v8::Function>&)’
npm ERR! npm ERR!    83 |   target->Set(className, f);
npm ERR! npm ERR!       |                           ^
npm ERR! npm ERR! In file included from /home/maurgi/.cache/node-gyp/15.14.0/include/node/node.h:63,
npm ERR! npm ERR!                  from ../src/addon.cpp:1:
npm ERR! npm ERR! /home/maurgi/.cache/node-gyp/15.14.0/include/node/v8.h:3716:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
npm ERR! npm ERR!  3716 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
npm ERR! npm ERR!       |                                     ^~~
npm ERR! npm ERR! /home/maurgi/.cache/node-gyp/15.14.0/include/node/v8.h:3716:37: note:   candidate expects 3 arguments, 2 provided
npm ERR! npm ERR! /home/maurgi/.cache/node-gyp/15.14.0/include/node/v8.h:3719:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
npm ERR! npm ERR!  3719 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
npm ERR! npm ERR!       |                                     ^~~
npm ERR! npm ERR! /home/maurgi/.cache/node-gyp/15.14.0/include/node/v8.h:3719:37: note:   candidate expects 3 arguments, 2 provided
npm ERR! npm ERR! In file included from ../src/addon.cpp:1:
npm ERR! npm ERR! ../src/addon.cpp: At global scope:
npm ERR! npm ERR! /home/maurgi/.cache/node-gyp/15.14.0/include/node/node.h:838:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
npm ERR! npm ERR!   838 |       (node::addon_register_func) (regfunc),                          \
npm ERR! npm ERR!       |                                           ^
npm ERR! npm ERR! /home/maurgi/.cache/node-gyp/15.14.0/include/node/node.h:872:3: note: in expansion of macro ‘NODE_MODULE_X’
npm ERR! npm ERR!   872 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
npm ERR! npm ERR!       |   ^~~~~~~~~~~~~
npm ERR! npm ERR! ../src/addon.cpp:164:1: note: in expansion of macro ‘NODE_MODULE’
npm ERR! npm ERR!   164 | NODE_MODULE(sha3, SHA3Hash::Init)
npm ERR! npm ERR!       | ^~~~~~~~~~~
npm ERR! npm ERR! make: *** [sha3.target.mk:115: Release/obj.target/sha3/src/addon.o] Error 1
npm ERR! npm ERR! gyp ERR! build error 
npm ERR! npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/maurgi/.nvm/versions/node/v15.14.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
npm ERR! npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! npm ERR! gyp ERR! System Linux 5.10.16.3-microsoft-standard-WSL2
npm ERR! npm ERR! gyp ERR! command "/home/maurgi/.nvm/versions/node/v15.14.0/bin/node" "/home/maurgi/.nvm/versions/node/v15.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! npm ERR! gyp ERR! cwd /home/maurgi/.npm/_cacache/tmp/git-clone-212ef9b3/node_modules/sha3
npm ERR! npm ERR! gyp ERR! node -v v15.14.0
npm ERR! npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! npm ERR! gyp ERR! not ok
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/maurgi/.npm/_logs/2021-08-20T02_30_43_898Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/maurgi/.npm/_logs/2021-08-20T02_30_45_322Z-debug.log
```

**Comment by smartins** [comment]
Also facing issues installing opensea.js. I'm trying with nodejs 16 and the latest version of web3 but that might be the problem, is going back to nodejs 8 really needed to install opensea.js? If so, I assume web3 also needs to be downgraded to a specific version.
