### ISSUE TITLE
Error on createSellOrder

### ISSUE THREAD

**Issue by jmxazd** [ProjectOpenSea/opensea-js#218]
opensea-js v1.2.1, 

const fixedPriceSellOrder = await seaport.createSellOrder({
    asset: {
      tokenId,
      tokenAddress: NFT_CONTRACT_ADDRESS,
    },
    startAmount: 0.05,
    expirationTime: Math.round(Date.now() / 1000 + 60 * 60 * 24),
    accountAddress: OWNER_ADDRESS,
  });

(node:20511) Error: Trading for this asset (ERC721) is not yet supported. Please contact us or check back later!
    at OpenSeaPort._getSchema (/Users/zxa2068/Desktop/opensea-creatures-master/node_modules/_opensea-js@1.2.1@opensea-js/lib/seaport.js:3076:19)
    at OpenSeaPort.<anonymous> (/Users/zxa2068/Desktop/opensea-creatures-master/node_modules/_opensea-js@1.2.1@opensea-js/lib/seaport.js:1991:39)
    at step (/Users/zxa2068/Desktop/opensea-creatures-master/node_modules/_opensea-js@1.2.1@opensea-js/lib/seaport.js:44:23)
    at Object.next (/Users/zxa2068/Desktop/opensea-creatures-master/node_modules/_opensea-js@1.2.1@opensea-js/lib/seaport.js:25:53)
    at /Users/zxa2068/Desktop/opensea-creatures-master/node_modules/_opensea-js@1.2.1@opensea-js/lib/seaport.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/zxa2068/Desktop/opensea-creatures-master/node_modules/_opensea-js@1.2.1@opensea-js/lib/seaport.js:15:12)
    at OpenSeaPort._makeSellOrder (/Users/zxa2068/Desktop/opensea-creatures-master/node_modules/_opensea-js@1.2.1@opensea-js/lib/seaport.js:1985:16)
    at OpenSeaPort.<anonymous> (/Users/zxa2068/Desktop/opensea-creatures-master/node_modules/_opensea-js@1.2.1@opensea-js/lib/seaport.js:592:55)
    at step (/Users/zxa2068/Desktop/opensea-creatures-master/node_modules/_opensea-js@1.2.1@opensea-js/lib/seaport.js:44:23)
(node:20511) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)

**Comment by lynnsir-102** [comment]
I also encountered the same problem. Has it been solved now @jmxazd

**Comment by esteban-OpenSea** [comment]
Are you still running into this issue? As a reminder please use the latest version of node and the SDK
