### ISSUE TITLE
Cannot read properties of null (reading 'address')

### ISSUE THREAD

**Issue by koin-marian** [ProjectOpenSea/opensea-js#330]
Happens when fetching an asset through getAsset:

TypeError: Cannot read properties of null (reading 'address')
    at Object.accountFromJSON (vendors~main.chunk.js:286871:22)
    at Object.transactionFromJSON (vendors~main.chunk.js:286856:24)
    at Object.assetEventFromJSON (vendors~main.chunk.js:286846:51)
    at Object.assetFromJSON (vendors~main.chunk.js:286817:41)
    at OpenSeaAPI.<anonymous> (vendors~main.chunk.js:279608:23)
    at step (vendors~main.chunk.js:279298:17)
    at Object.next (vendors~main.chunk.js:279229:14)
    at fulfilled (vendors~main.chunk.js:279183:24)

The problem is that some items have null for last_sale.transaction.to_account and the accountFromJSON method does not check for null and tries to access the 'address' property of 'to_account'.

**Comment by esteban-OpenSea** [comment]
Are you still running into this issue? As a reminder, please upgrade to the latest SDK and Node version.
