### ISSUE TITLE
_initializeProxy() fails

### ISSUE THREAD

**Issue by yogh333** [ProjectOpenSea/opensea-js#340]
Hi,

 Everytime I use _initializeProxy() function, I have an "Error: invalid address" issue returned by @0xproject:

Error: invalid address
    at inputAddressFormatter (/Users/jerome.caporossi/Documents/opensea-api/node_modules/@0xproject/web3-wrapper/node_modules/web3/lib/web3/formatters.js:274:11)
    at inputCallFormatter (/Users/jerome.caporossi/Documents/opensea-api/node_modules/@0xproject/web3-wrapper/node_modules/web3/lib/web3/formatters.js:74:24)
    at /Users/jerome.caporossi/Documents/opensea-api/node_modules/@0xproject/web3-wrapper/node_modules/web3/lib/web3/method.js:89:28
    at Array.map (<anonymous>)
    at Method.formatInput (/Users/jerome.caporossi/Documents/opensea-api/node_modules/@0xproject/web3-wrapper/node_modules/web3/lib/web3/method.js:88:32)
    at Method.toPayload (/Users/jerome.caporossi/Documents/opensea-api/node_modules/@0xproject/web3-wrapper/node_modules/web3/lib/web3/method.js:114:23)
    at Eth.send [as estimateGas] (/Users/jerome.caporossi/Documents/opensea-api/node_modules/@0xproject/web3-wrapper/node_modules/web3/lib/web3/method.js:139:30)
    at SolidityFunction.estimateGas (/Users/jerome.caporossi/Documents/opensea-api/node_modules/@0xproject/web3-wrapper/node_modules/web3/lib/web3/function.js:190:15)
    at /Users/jerome.caporossi/Documents/opensea-api/node_modules/@0xproject/utils/lib/promisify.js:58:36
    at new Promise (<anonymous>)
    at Object.<anonymous> (/Users/jerome.caporossi/Documents/opensea-api/node_modules/@0xproject/utils/lib/promisify.js:54:39)
    at step (/Users/jerome.caporossi/Documents/opensea-api/node_modules/@0xproject/utils/lib/promisify.js:32:23)
    at Object.next (/Users/jerome.caporossi/Documents/opensea-api/node_modules/@0xproject/utils/lib/promisify.js:13:53)
    at /Users/jerome.caporossi/Documents/opensea-api/node_modules/@0xproject/utils/lib/promisify.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jerome.caporossi/Documents/opensea-api/node_modules/@0xproject/utils/lib/promisify.js:3:12)

I do not undertsand why the error pops up from @0xproject while calling opensea-js API. The adress used to created proxy is correct (generated by my Metamask wallet).

Thanks for your help,
Kind regards,
Jerome

**Comment by esteban-OpenSea** [comment]
Are you still having this issue? Not sure what your code looks like but I have some suggestions:

1. Ensure you are passing valid arguments. 
2. Ensure you are passing a correctly formatted `address` property
