### ISSUE TITLE
'Unknown address - unable to sign transaction for this address' when trying to create sell order

### ISSUE THREAD

**Issue by vlademel** [ProjectOpenSea/opensea-js#342]
I'm trying to run the following code:

```
require('dotenv').config();

const Web3 = require('web3')
const opensea = require('opensea-js')
const HDWalletProvider = require("@truffle/hdwallet-provider");

const provider = new HDWalletProvider({
    mnemonic: process.env.MNEMONIC,
    providerOrUrl: process.env.INFURA_API_KEY,
    addressIndex: 3
});


const YOUR_API_KEY = process.env.OS_API_KEY
const seaport = new opensea.OpenSeaPort(provider, {
    networkName: opensea.Network.Rinkeby,
    apiKey: YOUR_API_KEY
})

const call = async () => {
    const accountAddress = process.env.ACCOUNT_ADDRESS
    const tokenId = 1
    const tokenAddress = "0x52ff80b0c767ef546a21c61de38d79024a0406f3"

    const offer = await seaport.createSellOrder({
        asset: {
            tokenAddress: tokenAddress,
            tokenId: tokenId,
            schemaName: 'ERC1155'
        },
        accountAddress: accountAddress,
        startAmount: 1
    })
    console.log(offer.expirationTime)
}

call()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });
```
But i'm being met with with the following error:
```
Error: Unknown address - unable to sign transaction for this address: "0x955e6dc3e8912115d913c4eBe72ffC9bd917B87e"
    at c:\Users\Vlad\Desktop\Current Projects\os_bot\node_modules\@truffle\hdwallet-provider\node_modules\web3-provider-engine\subproviders\hooked-wallet.js:492:35
    at c:\Users\Vlad\Desktop\Current Projects\os_bot\node_modules\@truffle\hdwallet-provider\node_modules\web3-provider-engine\subproviders\hooked-wallet.js:558:5
    at HookedWalletSubprovider.getAccounts (c:\Users\Vlad\Desktop\Current Projects\os_bot\node_modules\@truffle\hdwallet-provider\dist\index.js:140:17)
    at HookedWalletSubprovider.validateSender (c:\Users\Vlad\Desktop\Current Projects\os_bot\node_modules\@truffle\hdwallet-provider\node_modules\web3-provider-engine\subproviders\hooked-wallet.js:555:8)
    at HookedWalletSubprovider.validateTransaction (c:\Users\Vlad\Desktop\Current Projects\os_bot\node_modules\@truffle\hdwallet-provider\node_modules\web3-provider-engine\subproviders\hooked-wallet.js:490:8)
    at c:\Users\Vlad\Desktop\Current Projects\os_bot\node_modules\@truffle\hdwallet-provider\node_modules\web3-provider-engine\subproviders\hooked-wallet.js:123:22
    at nextTask (c:\Users\Vlad\Desktop\Current Projects\os_bot\node_modules\async\waterfall.js:16:14)
    at exports.default (c:\Users\Vlad\Desktop\Current Projects\os_bot\node_modules\async\waterfall.js:26:5)
    at HookedWalletSubprovider.handleRequest (c:\Users\Vlad\Desktop\Current Projects\os_bot\node_modules\@truffle\hdwallet-provider\node_modules\web3-provider-engine\subproviders\hooked-wallet.js:122:7)
    at next (c:\Users\Vlad\Desktop\Current Projects\os_bot\node_modules\@truffle\hdwallet-provider\node_modules\web3-provider-engine\index.js:200:18)
```
This address definitely exists. I have no idea what's happening here as HDWallet seems set up properly (was able to make a few read calls earlier with this wallet).
This code is essentially trying to sell a token I have on on the OS testnet using an account connected to Rinkeby.

**Comment by esteban-OpenSea** [comment]
Try to use private keys instead of mnemonic. Check this out: https://github.com/trufflesuite/truffle-hdwallet-provider#private-keys
