### ISSUE TITLE
After Upgrade to V 2.0.0 Cannot read property 'EIP712Domain' of undefined and "placeBid You declined to authorize your offer" 

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#372]
I just upgraded my version from Opensea to  the latest one of 2.0.0 and eversince then I get these 2 errors everytime I use the createBuyOrder function

`| TypeError: Cannot read property 'EIP712Domain' of undefined
nftapi_1    |     at Object.findTypeDependencies (/app/node_modules/@truffle/hdwallet-provider/node_modules/eth-sig-util/src/index.ts:230:47)
nftapi_1    |     at Object.encodeType (/app/node_modules/@truffle/hdwallet-provider/node_modules/eth-sig-util/src/index.ts:200:21)
nftapi_1    |     at Object.hashType (/app/node_modules/@truffle/hdwallet-provider/node_modules/eth-sig-util/src/index.ts:267:32)
nftapi_1    |     at Object.encodeData (/app/node_modules/@truffle/hdwallet-provider/node_modules/eth-sig-util/src/index.ts:96:33)
nftapi_1    |     at Object.hashStruct (/app/node_modules/@truffle/hdwallet-provider/node_modules/eth-sig-util/src/index.ts:256:32)
nftapi_1    |     at Object.sign (/app/node_modules/@truffle/hdwallet-provider/node_modules/eth-sig-util/src/index.ts:304:12)
nftapi_1    |     at Object.signTypedData (/app/node_modules/@truffle/hdwallet-provider/node_modules/eth-sig-util/src/index.ts:600:34)
nftapi_1    |     at HookedWalletSubprovider.signTypedMessage (/app/node_modules/@truffle/hdwallet-provider/src/index.ts:228:23)
nftapi_1    |     at /app/node_modules/web3-provider-engine/subproviders/hooked-wallet.js:390:18
nftapi_1    |     at nextTask (/app/node_modules/async/waterfall.js:16:14)
nftapi_1    |     at next (/app/node_modules/async/waterfall.js:23:9)
nftapi_1    |     at /app/node_modules/async/internal/onlyOnce.js:12:16
nftapi_1    |     at HookedWalletSubprovider.checkApproval (/app/node_modules/web3-provider-engine/subproviders/hooked-wallet.js:403:3)
nftapi_1    |     at /app/node_modules/web3-provider-engine/subproviders/hooked-wallet.js:389:30
nftapi_1    |     at nextTask (/app/node_modules/async/waterfall.js:16:14)
nftapi_1    |     at next (/app/node_modules/async/waterfall.js:23:9)
`

and also "You declined to authorize your offer"

What should I do?

**Comment by BeniSchlattmann** [comment]
same issue here. We cannot upgrade to the new SDK Version before this is fixed...

**Comment by p-real96** [comment]
... same issue huere

**Comment by nftbutler-ao** [comment]
same issue here.

**Comment by chapma26** [comment]
Looks like in the repo .nvmrc uses node v16.11.0. I removed my package-lock.json and and node_modules folder and did npm install thinking that might fix it but alas it did not.

**Comment by alexanderatallah** [comment]
Is everyone using hdwallet-provider? could be that there's an old version that does not support signTypedData_v4

**Comment by rjbks** [comment]
@alexanderatallah can you please provide an example of instantiating seaport and a provider that supports eth_signTypedData_v4?

**Comment by alexanderatallah** [comment]
Can you try using this for your provider? https://www.npmjs.com/package/@truffle/hdwallet-provider

**Comment by rjbks** [comment]
@alexanderatallah everyone in discord dev chat is saying that isn't working. They're now suggesting to use ethers.js provider. Ethers providers seem to be read only, signing needs a signer/wallet.

**Comment by lomboreb** [comment]
> Can you try using this for your provider? https://www.npmjs.com/package/@truffle/hdwallet-provider

I've tried with the lastest version of @truffle/hdwallet-provider (2.0.3), but I get the same error:

TypeError: Cannot read property 'EIP712Domain' of undefined
...
Error while bidding item: Error: You declined to authorize your offer

**Comment by nenadpnc** [comment]
Upgrade to `v2.0.1`, it's fixed with https://github.com/ProjectOpenSea/opensea-js/pull/388

**Comment by velmoorthi** [comment]
> Upgrade to `v2.0.1`, it's fixed with #388

great thanks!
