### ISSUE TITLE
createBuyOrder failes after upgrading to v2.0.0

### ISSUE THREAD

**Issue by meena-erian** [ProjectOpenSea/opensea-js#393]
Everything used to work fine until I upgraded to v2.0.0

Now every time I try to create a buy order it shows the following error:

Not enough token approved for trade: 0 approved to transfer 0xc778417e063141139fce010982780140aa0cd5ab

> index.js:119 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'await')
>     at push../node_modules/web3-provider-engine/index.js.Web3ProviderEngine.sendAsync (index.js:119:1)
>     at util.js:635:1
>     at CustomeCallbackWalletSubprovider.emitPayloadAsync (subprovider.ts:57:1)
>     at CustomeCallbackWalletSubprovider._populateMissingTxParamsAsync (base_wallet_subprovider.ts:121:1)
>     at CustomeCallbackWalletSubprovider.handleRequest (base_wallet_subprovider.ts:60:1)
>     at next (index.js:200:1)
>     at Web3ProviderEngine.push../node_modules/web3-provider-engine/index.js.Web3ProviderEngine._handleAsync (index.js:187:1)
>     at index.js:126:1

<html>
<body>
<div tabindex="-1" class="console-message-wrapper console-error-level console-selected" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; display: flex; border-top-width: ; border-top-style: ; border-top-color: var(--override-error-border-color); border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: var(--override-focused-message-border-color); background-color: var(--override-focused-message-background-color); --override-error-text-color:rgb(200 0 0); color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start;"><div class="console-message-stack-trace-wrapper" aria-label="index.js:119 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'await')
    at push../node_modules/web3-provider-engine/index.js.Web3ProviderEngine.sendAsync (index.js:119:1)
    at util.js:635:1
    at CustomeCallbackWalletSubprovider.emitPayloadAsync (subprovider.ts:57:1)
    at CustomeCallbackWalletSubprovider._populateMissingTxParamsAsync (base_wallet_subprovider.ts:121:1)
    at CustomeCallbackWalletSubprovider.handleRequest (base_wallet_subprovider.ts:60:1)
    at next (index.js:200:1)
    at Web3ProviderEngine.push../node_modules/web3-provider-engine/index.js.Web3ProviderEngine._handleAsync (index.js:187:1)
    at index.js:126:1 Stack table expanded" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace" style="display: inline-block; --monospace-font-size:12px; --monospace-font-family:consolas,lucida console,courier new,monospace; --source-code-font-size:12px; --source-code-font-family:consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">

push../node_modules/web3-provider-engine/index.js.Web3ProviderEngine.sendAsync | @ | index.js:119
-- | -- | --
  | (anonymous) | @ | util.js:635
  | emitPayloadAsync | @ | subprovider.ts:57
  | _populateMissingTxParamsAsync | @ | base_wallet_subprovider.ts:121
  | handleRequest | @ | base_wallet_subprovider.ts:60
  | next | @ | index.js:200
  | push../node_modules/web3-provider-engine/index.js.Web3ProviderEngine._handleAsync | @ | index.js:187
  | (anonymous) | @ | index.js:126
  | await in (anonymous) (async) |   |  
  | callCallback | @ | react-dom.development.js:3945
  | invokeGuardedCallbackDev | @ | react-dom.development.js:3994
  | invokeGuardedCallback | @ | react-dom.development.js:4056
  | invokeGuardedCallbackAndCatchFirstError | @ | react-dom.development.js:4070
  | executeDispatch | @ | react-dom.development.js:8243
  | processDispatchQueueItemsInOrder | @ | react-dom.development.js:8275
  | processDispatchQueue | @ | react-dom.development.js:8288
  | dispatchEventsForPlugins | @ | react-dom.development.js:8299
  | (anonymous) | @ | react-dom.development.js:8508
  | batchedEventUpdates$1 | @ | react-dom.development.js:22396
  | batchedEventUpdates | @ | react-dom.development.js:3745
  | dispatchEventForPluginEventSystem | @ | react-dom.development.js:8507
  | attemptToDispatchEvent | @ | react-dom.development.js:6005
  | dispatchEvent | @ | react-dom.development.js:5924
  | unstable_runWithPriority | @ | scheduler.development.js:468
  | runWithPriority$1 | @ | react-dom.development.js:11276
  | discreteUpdates$1 | @ | react-dom.development.js:22413
  | discreteUpdates | @ | react-dom.development.js:3756
  | dispatchDiscreteEvent | @ | react-dom.development.js:5889

</span></div></div></div></div></div><div tabindex="-1" class="console-message-wrapper console-error-level" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; border-top-width: ; border-top-style: ; border-top-color: transparent; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: var(--override-error-border-color); background-color: var(--override-console-error-background-color); color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><span is="ui-icon" class="message-level-icon spritesheet-smallicons smallicon-error" aria-label="Error" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: inline-block; flex: 1 1 auto; position: absolute; left: -17px; top: 4px; user-select: none; background-position: var(--spritesheet-position); background-image: var(--image-file-smallIcons); --spritesheet-position:-40px 70px; width: 10px; height: 10px;"></span><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start;"><div class="console-message-stack-trace-wrapper" aria-label="​ Uncaught ReferenceError: process is not defined
    at Object.4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at Object.8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at Object.8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at HTMLIFrameElement.e.onload (vendors~main.chunk.js:248356:324845) Stack table collapsed" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div aria-expanded="false" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span is="ui-icon" class="console-message-expand-icon spritesheet-smallicons smallicon-triangle-right icon-mask" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: inline-block; flex-shrink: 0; margin-bottom: -2px; --override-icon-mask-background-color:rgb(110 110 110); background-color: var(--override-icon-mask-background-color); -webkit-mask-position: var(--spritesheet-position); -webkit-mask-image: var(--image-file-smallIcons); --spritesheet-position:0px 10px; width: 10px; height: 10px;"></span></div></div></div></div></div><br class="Apple-interchange-newline">
</body>
</html>

I'm using the rinkeby testnet and I can confirm that I have enough weth because when I run getTokenBalance for the same account address and the same token address (ie the rinkeby weth token 0xc778417e063141139fce010982780140aa0cd5ab) and using the same Ethereum node, it shows that my WETH balance is  2910036999999493000 ether

**Comment by esteban-OpenSea** [comment]
Are you still having this issue? Are you using the most recent version of opensea-js?
