### ISSUE TITLE
seaport.fulfillOrder gives Address Not Found

### ISSUE THREAD

**Issue by MetalGear-cmd** [ProjectOpenSea/opensea-js#409]
So I am trying to Buy an asset by using the sdk, As soon as the fullfillOrdr() is executed, it checks for gas fee and other things and then gives the error as:

Sell order is valid: true
Orders matching: undefined
Order calldata matching: undefined
Fulfilling order with gas set to 249018
Error: ADDRESS_NOT_FOUND: My Wallet address (address trying to buy with)
    at MnemonicWalletSubprovider._findDerivedKeyInfoForAddress (C:\Users\Mohsin\Desktop\Listings Bot Updated\node_modules\@0x\subproviders\src\subproviders\mnemonic_wallet.ts:149:19)
    at MnemonicWalletSubprovider._privateKeyWalletForAddress (C:\Users\Mohsin\Desktop\Listings Bot Updated\node_modules\@0x\subproviders\src\subproviders\mnemonic_wallet.ts:137:37)
    at MnemonicWalletSubprovider.<anonymous> (C:\Users\Mohsin\Desktop\Listings Bot Updated\node_modules\@0x\subproviders\src\subproviders\mnemonic_wallet.ts:93:39)
    at Generator.next (<anonymous>)
    at C:\Users\Mohsin\Desktop\Listings Bot Updated\node_modules\@0x\subproviders\lib\src\subproviders\mnemonic_wallet.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Mohsin\Desktop\Listings Bot Updated\node_modules\@0x\subproviders\lib\src\subproviders\mnemonic_wallet.js:4:12)
    at MnemonicWalletSubprovider.signTransactionAsync (C:\Users\Mohsin\Desktop\Listings Bot Updated\node_modules\@0x\subproviders\lib\src\subproviders\mnemonic_wallet.js:89:16)
    at MnemonicWalletSubprovider.<anonymous> (C:\Users\Mohsin\Desktop\Listings Bot Updated\node_modules\@0x\subproviders\src\subproviders\base_wallet_subprovider.ts:66:49)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Mohsin\Desktop\Listings Bot Updated\node_modules\@0x\subproviders\lib\src\subproviders\base_wallet_subprovider.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Failed to authorize transaction: "ADDRESS_NOT_FOUND: 0x0901104C53f6bc215204843fD33d62958xxxxxxxxx..."
    at OpenSeaPort.<anonymous> (C:\Users\Mohsin\Desktop\Listings Bot Updated\node_modules\opensea-js\src\seaport.ts:4238:13)
    at step (C:\Users\Mohsin\Desktop\Listings Bot Updated\node_modules\opensea-js\lib\seaport.js:63:23)
    at Object.throw (C:\Users\Mohsin\Desktop\Listings Bot Updated\node_modules\opensea-js\lib\seaport.js:44:53)
    at rejected (C:\Users\Mohsin\Desktop\Listings Bot Updated\node_modules\opensea-js\lib\seaport.js:36:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Any help what I am doing wrong?

**Comment by esteban-OpenSea** [comment]
Are you using the latest opensea-js version?

**Comment by MetalGear-cmd** [comment]
> Are you using the latest opensea-js version?

Yes on the latest version of sdk this error still seems to popup
