### ISSUE TITLE
Unable to install opensea-js

### ISSUE THREAD

**Issue by wurdig-mich** [ProjectOpenSea/opensea-js#447]
Been trying to install the opensea-js in my react-app. Apparently the new git rules aint in my favor. Help!

```
yarn add opensea-js
yarn add v1.22.17
warning ../../../package.json: No license field
[1/4] 🔍  Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/ProjectWyvern/ethereumjs-abi.git
Directory: /Users/wurdig_mich/Development/React/opensea
Output:
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
warning opensea-js > fbemitter > fbjs > core-js@1.2.7: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning opensea-js > web3 > web3-bzz > swarm-js > mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
warning opensea-js > web3 > web3-eth > web3-eth-accounts > uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning opensea-js > web3 > web3-bzz > swarm-js > eth-lib > servify > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning opensea-js > web3 > web3-bzz > swarm-js > eth-lib > servify > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning opensea-js > web3 > web3-eth > web3-eth-ens > content-hash > cids@0.7.5: This module has been superseded by the multiformats module
warning opensea-js > web3 > web3-eth > web3-eth-ens > content-hash > multicodec@0.5.7: This module has been superseded by the multiformats module
warning opensea-js > web3 > web3-eth > web3-eth-ens > content-hash > cids > multicodec@1.0.4: This module has been superseded by the multiformats module
warning opensea-js > web3 > web3-bzz > swarm-js > eth-lib > servify > request > har-validator@5.1.5: this library is no longer supported
warning opensea-js > web3 > web3-eth > web3-eth-ens > content-hash > cids > multibase@0.6.1: This module has been superseded by the multiformats module
warning opensea-js > web3 > web3-eth > web3-eth-ens > content-hash > multihashes > multibase@0.7.0: This module has been superseded by the multiformats module
Error: Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/ProjectOpenSea/wyvern-js.git
Directory: /Users/wurdig_mich/Development/React/opensea
Output:
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
    at ProcessTermError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at new ProcessTermError (/usr/local/lib/node_modules/yarn/lib/cli.js:790:113)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:25783:17)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12)
Error: Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/ProjectOpenSea/wyvern-schemas.git
Directory: /Users/wurdig_mich/Development/React/opensea
Output:
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
    at ProcessTermError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at new ProcessTermError (/usr/local/lib/node_modules/yarn/lib/cli.js:790:113)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:25783:17)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12)
```

**Comment by esteban-OpenSea** [comment]
Try these two things:

1. Follow the documentation here: https://github.com/ProjectOpenSea/opensea-js#installation
2. The other times I've seen this error is because the SSH key has been removed/revoked. Make a new one and add it to your GitHub account.
3. Also, take a look at [this](https://stackoverflow.com/questions/70663523/the-unauthenticated-git-protocol-on-port-9418-is-no-longer-supported)

**Comment by esteban-OpenSea** [comment]
Just wanted to follow up on this. Are you still having this issue?

**Comment by teawaterwire** [comment]
having the same error when trying to install `opensea-js` on a Glitch.com project
```
npm ERR! git dep preparation failed
...
```

**Comment by July-Jio** [comment]
got the same error. has this been solved?

**Comment by inayatu** [comment]
Same error.  with node 16+ npm 8+

**Comment by freemavis** [comment]
same error: 
yarn 1.22.17 
node v16.14.0

**Comment by ai323** [comment]
same error using yarn

**Comment by Claytonn** [comment]
`yarn clean && yarn` worked for me with this error.

**Comment by esteban-OpenSea** [comment]
This is a duplicate ticket, please follow [this](https://github.com/ProjectOpenSea/opensea-js/issues/471) ticket for the latest updates on this issue to avoid confusion. I will go ahead and close.

https://github.com/ProjectOpenSea/opensea-js/issues/471
