### ISSUE TITLE
TypeError issue when creating a buy order

### ISSUE THREAD

**Issue by Tzeboys** [ProjectOpenSea/opensea-js#458]
Error:
```
[ERROR] 2022-04-11T06:10:37.750Z Offer failed TypeError: Cannot read property 'address' of null
    at accountFromJSON (C:\Users\Tzebo\OneDrive\Documents\GitHub\OpenseaBot\build\node_modules\opensea-js\lib\utils\utils.js:333:26)
    at transactionFromJSON (C:\Users\Tzebo\OneDrive\Documents\GitHub\OpenseaBot\build\node_modules\opensea-js\lib\utils\utils.js:319:48)
    at assetEventFromJSON (C:\Users\Tzebo\OneDrive\Documents\GitHub\OpenseaBot\build\node_modules\opensea-js\lib\utils\utils.js:307:47)
    at assetFromJSON (C:\Users\Tzebo\OneDrive\Documents\GitHub\OpenseaBot\build\node_modules\opensea-js\lib\utils\utils.js:280:68)
    at OpenSeaAPI.<anonymous> (C:\Users\Tzebo\OneDrive\Documents\GitHub\OpenseaBot\build\node_modules\opensea-js\lib\api.js:272:77)
    at step (C:\Users\Tzebo\OneDrive\Documents\GitHub\OpenseaBot\build\node_modules\opensea-js\lib\api.js:63:23)
    at Object.next (C:\Users\Tzebo\OneDrive\Documents\GitHub\OpenseaBot\build\node_modules\opensea-js\lib\api.js:44:53)
    at fulfilled (C:\Users\Tzebo\OneDrive\Documents\GitHub\OpenseaBot\build\node_modules\opensea-js\lib\api.js:35:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Code:
```
for (const nft of assets) {
  const tokenId = nft.tokenId;
  const contractAddress = nft.contractAddress;
  const schema = 'ERC721';

  await ratelimitOpensea();

  const offerCall = seaport.createBuyOrder({
      asset: {
          tokenId: tokenId,
          tokenAddress: contractAddress,
          schemaName: schema
      },
      accountAddress: walletAddress,
      // Value of the offer, in units of the payment token (or wrapped ETH if none is specified):
      startAmount: bidamount,
      expirationTime: Math.round(Date.now() / 1000 + 60 * 60 * 24) // 24 hours from now
  });
console.log(tokenId)
console.log(contractAddress)
console.log(walletAddress)
  offerCalls.push(offerCall);

  offerCall
      .then(function (offer) {
          console.log('[DEBUG]', new Date(), `Offer placed, expires in ${yargs.argv.offerExpiration}min`, offer.hash, offer.metadata.asset);
      })
      .catch(function (error) {
          console.log('[ERROR]', new Date(), 'Offer failed', error);
      })
  ;
}
```

**Comment by esteban-OpenSea** [comment]
Are you exporting your server?

**Comment by esteban-OpenSea** [comment]
Is this still an issue for you?

**Comment by Tzeboys** [comment]
> 

It is no longer an issue
