### ISSUE TITLE
Mainnet place offer error: Address 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 is not whitelisted

### ISSUE THREAD

**Issue by research-and-develop** [ProjectOpenSea/opensea-js#478]
Hello there,

I am trying to place an offer using `opensea-js`.
When working with **Rinkeby** testnet, everything works fine, but when I try to do it on the **Mainnet** I see the following response:

```
{
"jsonrpc": "2.0", 
"id": 1, 
"error": {
   "code": -32600, 
   "message": "Address 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 is not whitelisted"
}}
```
I see that this is the address of **WETH**, but I don't understand why it fails.

Usually the library is taking care to approve the required amount of **WETH**, at least this is how it works on the testnet.

My code:
```
try {
    const offer = await seaport.createBuyOrder({
        asset: {
            tokenId: 'some-token-id',
            tokenAddress: 'token-contract-address',
            schemaName: 'ERC721'
        },
        accountAddress: 'my-wallet-address',
        startAmount: '0.1',
        expirationTime: Math.round(new Date().getTime() / 1000) + 3600
    });

    console.log(`Bid placed (${asset.bid} WETH): ${offer.asset.openseaLink}`);
} catch (error) {
    console.log(`Failed to place bid for ${asset.address}(tokenId=${asset.tokenId})`);
    console.log(error.message + '\n');
    console.log(error.stack);
}

```

Full error log:

```
Error: Unknown Error: {"jsonrpc": "2.0", "id": 1, "error": {"code": -32600, "message": "Address 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 is not whitelisted"}}
{
  "originalError": {}
}
    at Object._fireError (/usr/src/app/node_modules/web3-utils/lib/index.js:49:17)
    at sendTxCallback (/usr/src/app/node_modules/web3-core-method/lib/index.js:548:30)
    at /usr/src/app/node_modules/web3-core-requestmanager/lib/index.js:299:20
    at /usr/src/app/node_modules/web3-provider-engine/index.js:232:9
    at /usr/src/app/node_modules/async/internal/once.js:12:16
    at replenish (/usr/src/app/node_modules/async/internal/eachOfLimit.js:61:25)
    at /usr/src/app/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/usr/src/app/node_modules/async/eachLimit.js:43:36)
    at /usr/src/app/node_modules/async/internal/doLimit.js:9:16
    at end (/usr/src/app/node_modules/web3-provider-engine/index.js:211:5)
    at Request._callback (/usr/src/app/node_modules/web3-provider-engine/subproviders/rpc.js:58:18)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

My environment:

opensea-js: ^3.0.2
nodeJS: v16.13.0

Thank you in advance.

**Comment by esteban-OpenSea** [comment]
What happens when you try a different contract address?

**Comment by research-and-develop** [comment]
Hi and thanks for your response.

What I did is updated opensea-js to 3.0.4 and now I see a similar error message.
The error appears even if I try to place a bid for different contract addresses and different tokenIds.

```
DEPRECATED: Please use providerUtils.standardizeOrThrow() instead
DEPRECATED: Please use providerUtils.standardizeOrThrow() instead
Not enough token approved for trade: 0 approved to transfer 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
Transaction started: Approving currency for trading
Transaction succeeded: Approving currency for trading
{
  code: -32603,
  message: 'Unknown Error: {"jsonrpc":"2.0","error":{"code":-32600,"message":"Address 0x7f268357a8c2552623316e2562d90e642bb538e5 is not whitelisted"},"id":1}',
  data: { originalError: {} }
}
Failed to place bid for 0xCONTRACT_ADDRESS(tokenId=TOKEN_ID)
You declined to authorize your offer
```
We can see from the log that now the library succeeds to interact with **0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2** (WETH address) but looks like something fails with **0x7f268357a8c2552623316e2562d90e642bb538e5** (Wyvern Exchange Contract).

I will try to update again if there is new version, but in any case bidding using different contract addresses and token ids results in this error. I am trying to bid with 0.01 WETH, could it be a problem?
