### ISSUE TITLE
seaport.fulfillOrder returns Error: ADDRESS_NOT_FOUND

### ISSUE THREAD

**Issue by MetalGear-cmd** [ProjectOpenSea/opensea-js#506]
I am trying to fulfillOrder on an asset using the latest SDK version and node version 16.13.8 and I get the following error this error has been around for more then a month now I have also tried older versions of the SDk as well but this error is still there:

Sell order is valid: true
Orders matching: undefined
Order calldata matching: undefined
Fulfilling order with gas set to 249072
Error: ADDRESS_NOT_FOUND: 0x9d36d9743ea81788645efe9c548c193db0fcd9dd
    at MnemonicWalletSubprovider._findDerivedKeyInfoForAddress (D:\Documents\Upwork\opensea-listings with email\node_modules\@0x\subproviders\src\subproviders\mnemonic_wallet.ts:144:19)
    at MnemonicWalletSubprovider._privateKeyWalletForAddress (D:\Documents\Upwork\opensea-listings with email\node_modules\@0x\subproviders\src\subproviders\mnemonic_wallet.ts:132:37)
    at MnemonicWalletSubprovider.<anonymous> (D:\Documents\Upwork\opensea-listings with email\node_modules\@0x\subproviders\src\subproviders\mnemonic_wallet.ts:88:39)
    at step (D:\Documents\Upwork\opensea-listings with email\node_modules\@0x\subproviders\lib\src\subproviders\mnemonic_wallet.js:45:23)
    at Object.next (D:\Documents\Upwork\opensea-listings with email\node_modules\@0x\subproviders\lib\src\subproviders\mnemonic_wallet.js:26:53)
    at D:\Documents\Upwork\opensea-listings with email\node_modules\@0x\subproviders\lib\src\subproviders\mnemonic_wallet.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Documents\Upwork\opensea-listings with email\node_modules\@0x\subproviders\lib\src\subproviders\mnemonic_wallet.js:16:12)
    at MnemonicWalletSubprovider.signTransactionAsync (D:\Documents\Upwork\opensea-listings with email\node_modules\@0x\subproviders\lib\src\subproviders\mnemonic_wallet.js:132:16)
    at MnemonicWalletSubprovider.<anonymous> (D:\Documents\Upwork\opensea-listings with email\node_modules\@0x\subproviders\src\subproviders\base_wallet_subprovider.ts:66:49)
    at step (D:\Documents\Upwork\opensea-listings with email\node_modules\@0x\subproviders\lib\src\subproviders\base_wallet_subprovider.js:56:23)
    at Object.next (D:\Documents\Upwork\opensea-listings with email\node_modules\@0x\subproviders\lib\src\subproviders\base_wallet_subprovider.js:37:53)
    at fulfilled (D:\Documents\Upwork\opensea-listings with email\node_modules\@0x\subproviders\lib\src\subproviders\base_wallet_subprovider.js:28:58)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
Error: Failed to authorize transaction: "ADDRESS_NOT_FOUND: 0x9d36d9743ea81788645efe9c548c193db0fcd9dd..."
    at OpenSeaPort.<anonymous> (D:\Documents\Upwork\opensea-listings with email\node_modules\opensea-js\src\seaport.ts:4275:13)
    at step (D:\Documents\Upwork\opensea-listings with email\node_modules\opensea-js\lib\seaport.js:63:23)
    at Object.throw (D:\Documents\Upwork\opensea-listings with email\node_modules\opensea-js\lib\seaport.js:44:53)
    at rejected (D:\Documents\Upwork\opensea-listings with email\node_modules\opensea-js\lib\seaport.js:36:65)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

Please somebody help me

**Comment by MetalGear-cmd** [comment]
I was able to solve this problem, a while ago just forgot to update it here. Turns out this error was showing when I had the wallet address in .env file. But when I moved it to the code and stored it directly in a cont this error stopped appearing.
