### ISSUE TITLE
createSellOrder - Error: API Error 400: ['Failed to extract transfer calldata']

### ISSUE THREAD

**Issue by Schwartz10** [ProjectOpenSea/opensea-js#59]
Hi @alexanderatallah ! I am trying to write a script to list assets on opensea via opensea.js, and I get the following error when calling `createSellOrder`:

```
Already approved proxy for all tokens
Order hashes match
(node:50361) UnhandledPromiseRejectionWarning: Error: API Error 400: ['Failed to extract transfer calldata']
    at OpenSeaAPI.<anonymous> (/Users/jonathanschwartz/Documents/Collectible/node_modules/opensea-js/src/api.ts:418:11)
    at step (/Users/jonathanschwartz/Documents/Collectible/node_modules/opensea-js/lib/api.js:40:23)
    at Object.next (/Users/jonathanschwartz/Documents/Collectible/node_modules/opensea-js/lib/api.js:21:53)
    at fulfilled (/Users/jonathanschwartz/Documents/Collectible/node_modules/opensea-js/lib/api.js:12:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I've followed this example - https://github.com/ProjectOpenSea/opensea-creatures/blob/master/scripts/sell.js#L64

```js
const BASE_DERIVATION_PATH = `44'/60'/0'/0`;

const mnemonicWalletSubprovider = new MnemonicWalletSubprovider({
  mnemonic,
  baseDerivationPath: BASE_DERIVATION_PATH,
});

const infuraRpcSubprovider = new RPCSubprovider({
  rpcUrl,
});

const providerEngine = new Web3ProviderEngine();
providerEngine.addProvider(mnemonicWalletSubprovider);
providerEngine.addProvider(infuraRpcSubprovider);
providerEngine.start();

const seaport = new OpenSeaPort(
    providerEngine,
    {
      networkName: Network.Rinkeby,
    },
    (arg) => console.log(arg)
);

const asset = await seaport.api.getAsset({
      tokenAddress: CONTRACT_ADDR,
      tokenId: TOKEN_ID,
});
// the asset comes back here with all the correct information
console.log(asset);

const listing = await seaport.createSellOrder({
    asset: {
      tokenAddress: CONTRACT_ADDR,
      tokenId: TOKEN_ID
    },
    accountAddress: OWNER_ADDRESS,
    startAmount: 1,
    expirationTime: 0,
});
// ERROR
```

I've validated my account is unlocked and able to sign messages:

```js
  const w3 = new Web3(providerEngine);
  w3.eth
    .sign("message to sign", OWNER_ADDRESS)
    .then(console.log);
// prints a signature
```

**Comment by alexanderatallah** [comment]
what is your `CONTRACT_ADDR`? if it is not ERC721, you need to specify it as your `schemaName` inside the `asset` object

**Comment by Schwartz10** [comment]
That's it. Thank you. Can i add this to the docs somewhere? Happy to submit a PR for that!

**Comment by alexanderatallah** [comment]
Would love that! the docs are just the README
