### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'then') when doing production build

### ISSUE THREAD

**Issue by rahulretnan** [ProjectOpenSea/opensea-js#603]
Getting this error when doing react production build while using 
```
const order = await openSeaSdk.api.getOrderLegacyWyvern({
            asset_contract_address: nft?.token_address,
            token_id: nft?.token_id,
          });
```

```
TypeError: Cannot read properties of undefined (reading 'then')
    at a.includes.t.sendAsync (main.746fc96e1ef5c702.esm.js:2:535682)
    at bound  (main.746fc96e1ef5c702.esm.js:2:16111892)
    at h.<anonymous> (main.746fc96e1ef5c702.esm.js:2:1451668)
    at Generator.next (<anonymous>)
    at main.746fc96e1ef5c702.esm.js:2:1440404
    at new Promise (<anonymous>)
    at r (main.746fc96e1ef5c702.esm.js:2:1440149)
    at h.sendRawPayloadAsync (main.746fc96e1ef5c702.esm.js:2:1451395)
    at h.<anonymous> (main.746fc96e1ef5c702.esm.js:2:1449636)
    at Generator.next (<anonymous>)
    at main.746fc96e1ef5c702.esm.js:2:1440404
    at new Promise (<anonymous>)
    at r (main.746fc96e1ef5c702.esm.js:2:1440149)
    at h.callAsync (main.746fc96e1ef5c702.esm.js:2:1449352)
    at l.<anonymous> (main.746fc96e1ef5c702.esm.js:2:476902)
    at Generator.next (<anonymous>)
    at o (main.746fc96e1ef5c702.esm.js:2:471288)
```
This is not causing any issue while doing normal npm run dev, but when I do a production build this happens
Please help me resolve this issue

**Comment by jtaaa** [comment]
Hi @rahulretnan, can you confirm that you are experiencing the issue on version 4.0.3? A fix for this issue (for NPM users) was included in the latest release yesterday. For yarn users adding the following resolution should work as a temporary solution
```
  "resolutions": {
    "@0x/utils": "https://github.com/ProjectOpensea/0x-tools/raw/provider-patch/utils/0x-utils-6.5.0.tgz"
  }
```

**Comment by jtaaa** [comment]
Try upgrading npm cli to greater than version 8.5.2

**Comment by SMLaursen** [comment]
> we are currently using opensea-js 4.0.2. Tried installing 4.0.3 but I'm having some error installing latest version.

Same, is this what you're experiencing? :
https://github.com/ProjectOpenSea/opensea-js/issues/604
