### ISSUE TITLE
Error: missing revert data in call exception; Transaction reverted without a reason string 

### ISSUE THREAD

**Issue by qq578728** [ProjectOpenSea/opensea-js#612]
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85","data":"0x6352211e41eef36197985923311545a76c97197592a74e92bcf78b9eea70c14ea99bf0c3","accessList":null}, error={"code":-32000,"message":"execution reverted"}, code=CALL_EXCEPTION, version=providers/5.6.8)
    at Logger.makeError (D:\kaifa\xxxxxxxxxxxx\bidBot\node_modules\@ethersproject\logger\lib\index.js:233:21)
    at Logger.throwError (D:\kaifa\xxxxxxxxxxxx\bidBot\node_modules\@ethersproject\logger\lib\index.js:242:20)
    at checkError (D:\kaifa\xxxxxxxxxxxx\bidBot\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:108:16)
    at Web3Provider.<anonymous> (D:\kaifa\xxxxxxxxxxxx\bidBot\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:703:47)
    at step (D:\kaifa\xxxxxxxxxxxx\bidBot\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:48:23)
    at Object.throw (D:\kaifa\xxxxxxxxxxxx\bidBot\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:29:53)
    at rejected (D:\kaifa\xxxxxxxxxxxx\bidBot\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'missing revert data in call exception; Transaction reverted without a reason string',
  code: 'CALL_EXCEPTION',
  data: '0x',
  transaction: {
    to: '0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85',
    data: '0x6352211e41eef36197985923311545a76c97197592a74e92bcf78b9eea70c14ea99bf0c3',
    accessList: null
  },
  error: { code: -32000, message: 'execution reverted' }
}

**Comment by Lebski** [comment]
There is an error calling `ownerOf(unit256)` in your contract `0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85` 

https://www.4byte.directory/signatures/?bytes4_signature=0x6352211
