### ISSUE TITLE
Error: API Error 400: Outstanding order to wallet balance ratio exceeds allowed limit.

### ISSUE THREAD

**Issue by MetalGear-cmd** [ProjectOpenSea/opensea-js#622]
hey so _ am trying to make bids on assets and I have a list of 10000 Assets, after making successful bids on around 2000 assets I started seeing this message:

Making Bid on asset: "5918.eth"
Error: API Error 400: Outstanding order to wallet balance ratio exceeds allowed limit.
at OpenSeaAPI.<anonymous> (C:\node_modules\opensea-js\lib\api.js:592:31)
at step (C:\node_modules\opensea-js\lib\api.js:63:23)
at [Object.next](http://object.next/) (C:\node_modules\opensea-js\lib\api.js:44:53)
at fulfilled (C:\node_modules\opensea-js\lib\api.js:35:58)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

How do I fix it, is it related to "You can make offers on 1000x the balance in your wallet mentioned in the docs"?
Thanks.
@jtaaa

**Comment by manikr91** [comment]
Its in their documentation:

https://github.com/ProjectOpenSea/opensea-js#offer-limits
