### ISSUE TITLE
fulfillOrderLegacyWyvern not working after webpack build with minimize:true

### ISSUE THREAD

**Issue by roadmanfong** [ProjectOpenSea/opensea-js#634]
It works well if  code is not minimized.

Here is the error message
```log
provider_utils.ts:89 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'then')
    at i.includes.t.sendAsync (provider_utils.ts:89:39)
    at bound  (rng-browser.js:647:16)
    at e.<anonymous> (web3_wrapper.ts:782:32)
    at l (superPropBase.js:86:17)
    at Generator._invoke (superPropBase.js:66:24)
    at Generator.next (superPropBase.js:117:21)
    at utils.ts:51:114
    at new Promise (<anonymous>)
    at c (utils.ts:51:114)
    at e.value (web3_wrapper.ts:769:41)
```

I created a repo to reproduce this issue
https://github.com/roadmanfong/opensea-demo

Please let me know if there is any solution, thx

**Comment by jtaaa** [comment]
Hi @roadmanfong thanks for the repro repo. The solution is to add the following yarn resolution to your package.json
```
  "resolutions": {
    "@0x/utils": "https://github.com/ProjectOpensea/0x-tools/raw/provider-patch/utils/0x-utils-6.5.0.tgz"
  }
```

Going to close this but please ping me here or in a separate issue if you're still encountering issues

**Comment by roadmanfong** [comment]
It works, I didn't noticed it on Readme file. Thanks a lot.
