### ISSUE TITLE
Transfer calldata doesn't match.

### ISSUE THREAD

**Issue by maximedrn** [ProjectOpenSea/opensea-js#656]
Hello,

I'm experimenting the OpenSea API by following the documentation. I met several errors that I managed to correct by reading the different issues already present. However, I encounter an error that I can't fix.

I'm trying to list a test NFT manually uploaded to OpenSea (without contract), so it's on the default OpenSea Shared storefront contract.
Unfortunately I can't do it and I get this error:

```
Error: API Error 400: Invalid request: ["Shared storefront is not configured for Seaport offers and listings. Please use Wyvern instead."]
    at OpenSeaAPI.<anonymous> (c:\Users\...\Desktop\node_modules\opensea-js\lib\api.js:592:31)
    at step (C:\Users\...\Desktop\node_modules\opensea-js\lib\api.js:63:23)
    at Object.next (C:\...\maxim\Desktop\node_modules\opensea-js\lib\api.js:44:53)
    at fulfilled (C:\Users\...\Desktop\node_modules\opensea-js\lib\api.js:35:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Here is the code I use:

```js
import HDWalletProvider from '@truffle/hdwallet-provider';
import WyvernSchemaName from 'opensea-js/lib/types.js';
import { OpenSeaSDK, Network } from 'opensea-js';


const MNEMONIC = ''; // Recovery phrase.
const ALCHEMY_API_KEY = ''; // Alchemy API key.
const API_KEY = ''; // OpenSea API key.

const NETWORK = 'mainnet';
const OWNER_ADDRESS = ''; // Ethereum address.
const TOKEN_ADDRESS = '0x495f947276749ce646f68ac8c248420045cb7b5e'; // https://opensea.io/collection/this/...
const TOKEN_ID = ''; // https://opensea.io/collection/.../this

const START_AMOUNT = 0.022;
const EXPIRATION_TIME = Math.round(Date.now() / 1000 + 60 * 60 * 24 * 1); // = 1 day.


const provider = new HDWalletProvider({
    mnemonic: MNEMONIC,
    providerOrUrl: `https://eth-${NETWORK}.alchemyapi.io/v2/${ALCHEMY_API_KEY}`,
    addressIndex: 1
});

const openseaSDK = new OpenSeaSDK(provider, {
    networkName: NETWORK === 'mainnet' || NETWORK === 'live' ? Network.Main : Network.Rinkeby,
    apiKey: API_KEY
}, arg => console.log(arg));


async function main() {
    console.log(`Listing an item on Fixed Price to ${OWNER_ADDRESS}.`);
    const fixedPriceSellOrder = await openseaSDK.createSellOrder({
        asset: {
            tokenId: TOKEN_ID,
            tokenAddress: TOKEN_ADDRESS,
            schemaName: WyvernSchemaName.ERC1155
        },
        startAmount: START_AMOUNT,
        expirationTime: EXPIRATION_TIME,
        accountAddress: OWNER_ADDRESS
    }).catch(error => console.log(error));
    console.log(`Successfully listed the item:\n${fixedPriceSellOrder.asset.openseaLink}\n`);
}

main();

```

And here is the `package.json` file used with the version of each module:

```json
{
    "type": "module",
    "dependencies": {
        "@truffle/hdwallet-provider": "^2.0.10",
        "opensea-js": "^4.0.4"
    }
}

```

Thanks in advance to the people who will want to help me 🙂.

**Comment by plondon** [comment]
`createBuyOrderLegacyWyvern` and `createSellOrderLegacyWyvern

**Comment by maximedrn** [comment]
Thank you very much! Now it goes a little further but I have a new problem. Here it is:

```
Already approved proxy for all tokens
Error: API Error 400: ["Transfer calldata doesn't match."]
```

I look at the [#385](https://github.com/ProjectOpenSea/opensea-js/issues/385) and [#517](https://github.com/ProjectOpenSea/opensea-js/issues/517) but none of them solve this problem.

**Comment by maximedrn** [comment]
I have corrected this problem. I replaced `WyvernSchemaName.ERC1155` with `ERC1155`.
Take a look at this problem: https://stackoverflow.com/questions/67265032/listing-nft-on-opensea-via-js-api-failed-to-extract-transfer-calldata-error-400
