### ISSUE TITLE
API Error 400: OpenSea fees are required to post this order.

### ISSUE THREAD

**Issue by jackwolt** [ProjectOpenSea/opensea-js#698]
Getting this error today on createSellOrder method:

`Error: API Error 400: OpenSea fees are required to post this order.
`

at OpenSeaAPI.<anonymous> (/app/node_modules/opensea-js/lib/api.js:592:31)
at step (/app/node_modules/opensea-js/lib/api.js:63:23)
at Object.next (/app/node_modules/opensea-js/lib/api.js:44:53)
at fulfilled (/app/node_modules/opensea-js/lib/api.js:35:58)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

For listing through the site there are no errors and requests to pay a fees. Have conditions changed for the API or is it just a bug?

**Comment by RelaxedDong** [comment]
+1

**Comment by RelaxedDong** [comment]
__error Error: API Error 400: OpenSea fees are required to post this order.
    at OpenSeaAPI.<anonymous> (/root/workspace/opensea_order/node_modules/opensea-js/lib/api.js:495:31)
    at step (/root/workspace/opensea_order/node_modules/opensea-js/lib/api.js:63:23)
    at Object.next (/root/workspace/opensea_order/node_modules/opensea-js/lib/api.js:44:53)
    at fulfilled (/root/workspace/opensea_order/node_modules/opensea-js/lib/api.js:35:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
undefined

**Comment by hoanghiep** [comment]
+1

**Comment by sunwrobert** [comment]
This is fixed now, please update to the latest `opensea-js`: 4.0.7
