### ISSUE TITLE
OpenSeaSDK.fulfillOrder() throws UNPREDICTABLE_GAS_LIMIT error (with reproduction code)

### ISSUE THREAD

**Issue by AydinGokce** [ProjectOpenSea/opensea-js#711]
Hello, 

`OpenSeaSDK.fulfillOrder()` is throwing an `UNPREDICTABLE_GAS_LIMIT` error. I'm on the Rinkeby chain. 

I haven't been able to figure out the cause, so I included the steps to reproduce below.

Node version: `16.13.0`

Package info:
```
"dependencies": {
    "@0x/subproviders": "^6.6.5",
    "@truffle/hdwallet-provider": "^2.0.14",
    "api": "^4.5.2",
    "body-parser": "^1.18.3",
    "concurrently": "^3.5.1",
    "ethers": "^5.6.9",
    "express": "^4.16.3",
    "mysql": "^2.15.0",
    "opensea-js": "^4.0.7",
    "uuid": "^8.3.2",
    "web3-provider-engine": "^16.0.4",
    "websocket": "^1.0.34",
    "ws": "^8.8.0"
  },
```
Before reproducing, you need the following

1. Some Infura project ID
2. Private key for some wallet with >0.01 Rinkeby ETH
3. Opensea API key (This might be optional as the same error occurs without it)

Code to reproduce:
```
// define keys (normally environment variables)
let keys = {}
keys.OS_API_KEY = "some-OS-api-key"
keys.OS_NETWORK = "rinkeby"
keys.WEB3_INFURA_PROJECT_ID = "some-infura-project-id"
keys.PURCHASE_WALLET_PRIVATE_KEY = "some-other-wallet-private-key"
keys.WEB3_RPC_URL = "https://" + keys.OS_NETWORK + ".infura.io/v3/" + keys.WEB3_INFURA_PROJECT_ID
keys.WEB3_NETWORK_CHAINID = 4

// import SDK and provider
const { OpenSeaSDK} = require("opensea-js");
const HDWalletProvider = require("@truffle/hdwallet-provider");
const Web3 = require('web3');

console.debug("keys: ", keys)

// instantiate wallet provider & web3
let provider = new HDWalletProvider({
    privateKeys: [keys.PURCHASE_WALLET_PRIVATE_KEY],
    providerOrUrl: keys.WEB3_RPC_URL,
    chainId: keys.WEB3_NETWORK_CHAINID
});

const web3 = new Web3(provider);

// add wallet to account
web3.eth.accounts.wallet.add(keys.PURCHASE_WALLET_PRIVATE_KEY);

// assume here that purchaseWallet contains more than enough eth to fulfill the order
const purchaseWallet = web3.eth.accounts.wallet[0];

// instantiate SDK
const openseaSDK = new OpenSeaSDK(provider, { networkName: keys.OS_NETWORK, apiKey: keys.OS_API_KEY, useReadOnlyProvider: false }, console.debug);

// OrderV2 object
orders = [
/*
    Copy-paste the full sample OrderV2 JSON as-is into this array
    Copy-paste from here: https://pastebin.com/80CRVMcZ
    For reference, this is the sell order: https://testnets.opensea.io/assets/rinkeby/0x0fc9a1c9d38fc795d8292a77a1b1413bc5cb6f21/1
*/
]

// This is what fails
openseaSDK.fulfillOrder({
            order: orders[0],
            accountAddress: purchaseWallet.address,
})
```
Full error message:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x9F2849813D4235CebF85C4b525Dd7549A13d9AE5","to":"0x00000000006c3852cbEf3e08E8dF289169EdE581","value":{"type":"BigNumber","hex":"0x11c37937e08000"},"data":"0xfb0f3ee1000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001151c96347b0000000000000000000000000004e574d7015e34235749f9406507b5471b5bf8bbd00000000000000000000000000000000e88fe2628ebc5da81d2b3cead633e89e0000000000000000000000000fc9a1c9d38fc795d8292a77a1b1413bc5cb6f210000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000003200000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000062f07a8e000000000000000000000000000000000000000000000000000000006319590e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0a82a94701fe0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f00000000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f00000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000071afd498d0000000000000000000000000008de9c5a032463c561423387a9648c5c7bcc5bc9000000000000000000000000000000000000000000000000000000000000000416acaeeed9796457f979d20a099a97c57b969ce440d4090eee5fdfb12adc0a2a156202c381601e2f38a27a559066b40cc43529fd42d91832f800a9d0cbc49f8911b00000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":3,"data":"0xee9e0e637d4956c0427f59eea57ea43ed3d7113a7b0c3c4c91552cae39870e664fa7965e","message":"execution reverted"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.0)
    at Logger.makeError (/path/to/my/app/packages/server/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/path/to/my/app/packages/server/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at checkError (/path/to/my/app/packages/server/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:122:20)
    at Web3Provider.<anonymous> (/path/to/my/app/packages/server/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:751:47)
    at step (/path/to/my/app/packages/server/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/path/to/my/app/packages/server/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/path/to/my/app/packages/server/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'execution reverted',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  method: 'estimateGas',
  transaction: {
    from: '0x9F2849813D4235CebF85C4b525Dd7549A13d9AE5',
    to: '0x00000000006c3852cbEf3e08E8dF289169EdE581',
    value: BigNumber { _hex: '0x11c37937e08000', _isBigNumber: true },
    data: '0xfb0f3ee1000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001151c96347b0000000000000000000000000004e574d7015e34235749f9406507b5471b5bf8bbd00000000000000000000000000000000e88fe2628ebc5da81d2b3cead633e89e0000000000000000000000000fc9a1c9d38fc795d8292a77a1b1413bc5cb6f210000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000003200000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000062f07a8e000000000000000000000000000000000000000000000000000000006319590e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0a82a94701fe0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f00000000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f00000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000071afd498d0000000000000000000000000008de9c5a032463c561423387a9648c5c7bcc5bc9000000000000000000000000000000000000000000000000000000000000000416acaeeed9796457f979d20a099a97c57b969ce440d4090eee5fdfb12adc0a2a156202c381601e2f38a27a559066b40cc43529fd42d91832f800a9d0cbc49f8911b00000000000000000000000000000000000000000000000000000000000000',
    accessList: null
  },
  error: {
    code: 3,
    data: '0xee9e0e637d4956c0427f59eea57ea43ed3d7113a7b0c3c4c91552cae39870e664fa7965e',
    message: 'execution reverted'
  }
}
```
Any insights would be much appreciated, feel free to request additional information.  

Thanks!

**Comment by FloUz-ai** [comment]
I have the exact same issue and I cant figure out, where it comes from. Any news about it its been hours I am looking for an answer ?

**Comment by trivonhan** [comment]
+1 problem

**Comment by DamonXiong** [comment]
I have the same problem when I use fulfillOrder with goerli.
`Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0xC94f4D2024E0eC8A0b4C93EB20c99E590DF63573","to":"0x00000000006c3852cbEf3e08E8dF289169EdE581","value":{"type":"BigNumber","hex":"0x038d7ea4c68000"},"data":"0xfb0f3ee1000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000376c1e0a7f0000000000000000000000000006c6c2d0d50fd789efecd2e31f64d936fb7ae3e3b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000bcbcfe01803f2b5f83753a1448b0af29b71ef5680000000000000000000000000000000000000000000000000000000000000cd7000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000063a08c9e000000000000000000000000000000000000000000000000000000006415e21f3000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000316b04361da1fe840000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f00000000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f00000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000016bcc41e90000000000000000000000000000000a26b00c1f0df003000390027140000faa7190000000000000000000000000000000000000000000000000000000000000040c2fbd47b0a1d78bcd112a9a186420620700ec5224d3ef0813a85029736a4334cdbea133d5268df17047f61b61970ef5364115e324c4d4a0368c0062233b62d83c5d24601","accessList":null}, error={"code":-32603,"message":"execution reverted","data":{"originalError":{"code":3,"data":"0xfb5014fc3d83fae14fee5990e2c80ebf07daabf25c9ff4b97e23745d15d19970acc1fc56","message":"execution reverted"}}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)`

**Comment by nickyoung92** [comment]
+1. Cant find any info in docs. Can devs do something?

**Comment by leoxie838** [comment]
some problem....

**Comment by pixelpawnshop** [comment]
Im experiencing the same problem how did you solved this?
