### ISSUE TITLE
Error: Unsupported method: eth_sendTransaction. Alchemy does not hold users' private keys.

### ISSUE THREAD

**Issue by trivonhan** [ProjectOpenSea/opensea-js#782]
When I call createSellOrder with openseaSDK, it throws error
```
Error: Unsupported method: eth_sendTransaction. Alchemy does not hold users' private keys. See available methods at https://docs.alchemy.com/alchemy/documentation/apis
    at /home/madtik/codelight/opensea-integrate/node_modules/@ethersproject/providers/src.ts/web3-provider.ts:71:35
    at /home/madtik/codelight/opensea-integrate/node_modules/web3/node_modules/web3-providers-http/lib/index.js:124:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I tried to add wallet address to web3.eth: `web3.eth.accounts.wallet.add(process.env.PRIVATE_KEY)` but it still get error.
Here is full of my source code:
```
import {
  OpenSeaPort as _OpenSeaPort,
  Network as _Network,
  OpenSeaSDK,
} from 'opensea-js';
import { WyvernSchemaName } from 'opensea-js/lib/types';
const OpenSeaPort = _OpenSeaPort;
const Network = _Network;
// import { MnemonicWalletSubprovider } from '@0x/subproviders';
// import RPCSubprovider from 'web3-provider-engine/subproviders/rpc';
// import Web3ProviderEngine from 'web3-provider-engine';
import * as dotenv from 'dotenv';
dotenv.config();

// eslint-disable-next-line @typescript-eslint/no-var-requires
const Web3 = require('web3');
async opensea() {
    const web3 = new Web3(
      'https://eth-goerli.g.alchemy.com/v2/process.env.ALCHEMY_KEY',
    );
    await web3.eth.accounts.wallet.add(process.env.PRIVATE_KEY);

    const provider = web3.currentProvider;

    console.log('provider', provider);
    const openseaSDK = new OpenSeaSDK(provider, {
      networkName: Network.Goerli,
    });

    // console.log('openseaSDK', openseaSDK);

    const assetBalance = await openseaSDK.getAssetBalance({
      accountAddress: '0x5C845F19EB923eEE213b620c12cc6D1d4E6E3506',
      asset: {
        tokenId: '0',
        tokenAddress: '0x1BAC1C2c2d23FcDaE91d63ff41a84f9F1c1C8aBF',
      },
    });
    console.log('assetBalance', assetBalance);

    const tokenBalance = await openseaSDK.getTokenBalance({
      accountAddress: '0x5C845F19EB923eEE213b620c12cc6D1d4E6E3506',
      tokenAddress: '0x1BAC1C2c2d23FcDaE91d63ff41a84f9F1c1C8aBF',
    });
    console.log('tokenBalance', tokenBalance);

    const createSellOrder = await openseaSDK.createSellOrder({
      asset: {
        tokenId: '0',
        tokenAddress: '0x1BAC1C2c2d23FcDaE91d63ff41a84f9F1c1C8aBF',
      },
      accountAddress: '0x5C845F19EB923eEE213b620c12cc6D1d4E6E3506',
      startAmount: 0.1,
    });
    console.log('createSellOrder', createSellOrder);
  }
```
Anyone has idea to help me?

**Comment by saivineeth1074** [comment]
You need to change your 'provider' variable. Below code is working for me.

const HDWalletProvider = require("@truffle/hdwallet-provider");

const provider = new HDWalletProvider({
    mnemonic: "fill this", // this is basically the secret recovery phrase in your metamask wallet
    providerOrUrl: 'https://eth-goerli.g.alchemy.com/v2/process.env.ALCHEMY_KEY',
    addressIndex: 0
});

Let me know if this works!
