### ISSUE TITLE
Error: Unknown schema name: undefined at getAssetItemType

### ISSUE THREAD

**Issue by kevgithub** [ProjectOpenSea/opensea-js#827]
Error: Unknown schema name: undefined at getAssetItemType (/data1/node/opensea/node_modules/opensea-js/lib/utils/utils.js:1083:19) at /data1/node/opensea/node_modules/opensea-js/lib/sdk.js:546:56 at Array.map () at OpenSeaSDK.getAssetItems (/data1/node/opensea/node_modules/opensea-js/lib/sdk.js:543:23) at OpenSeaSDK. (/data1/node/opensea/node_modules/opensea-js/lib/sdk.js:647:48) at step (/data1/node/opensea/node_modules/opensea-js/lib/sdk.js:63:23) at Object.next (/data1/node/opensea/node_modules/opensea-js/lib/sdk.js:44:53) at fulfilled (/data1/node/opensea/node_modules/opensea-js/lib/sdk.js:35:58) at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by kevgithub** [comment]
contract : 0x9d8a23be4b1347f30a5c5cf79350b87bddba4177 , error happened when making listing
