### ISSUE TITLE
TypeError: provider.getNetwork is not a function

### ISSUE THREAD

**Issue by Krake24** [ProjectOpenSea/opensea-js#882]
Getting this error since today (haven't used it two weeks prior):

  ```
TypeError: provider.getNetwork is not a function
      at new MulticallProvider (/home/XXX/node_modules/@0xsequence/multicall/dist/0xsequence-multicall.cjs.dev.js:348:20)
      at new Seaport (/home/XXX/node_modules/@opensea/seaport-js/lib/seaport.js:214:34)
      at new OpenSeaSDK (/home/XXX/node_modules/opensea-js/lib/sdk.js:138:24)
      at main (/home/XXX/offer.js:36:21)
      at Object.<anonymous> (/home/XXX/offer.js:65:1)
      at Module._compile (node:internal/modules/cjs/loader:1105:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
      at node:internal/main/run_main_module:17:47
```

**Comment by Krake24** [comment]
A version update has solved this issue (which I thought I had done)

**Comment by mohsinkc** [comment]
can you share your initial code and also which version solved this issue I am having this issue on the latest version
My code is below:
const providerOrUrl = "https://" + NETWORK + ".infura.io/v3/" + NODE_API_KEY;

const provider = new HDWalletProvider(privateKey, providerOrUrl);
const openseaSDK = new OpenSeaSDK(provider, {
  networkName: Network.Main,
  apiKey: API_KEY,
});
