### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'status')

### ISSUE THREAD

**Issue by pi9min** [ProjectOpenSea/opensea-js#931]
Hello! OpenSea Developer,

I am using the OpenSea SDK in a service running on Google AppEngine, and I frequently encounter the following error when executing `fulfillOrder` . (The transaction hash is masked)

```
No receipt found for <<transaction hash>>
/layers/google.nodejs.yarn/yarn_modules/node_modules/opensea-js/lib/utils/utils.js:220
status_1 = receipt.status;
^
TypeError: Cannot read properties of null (reading 'status')
at /layers/google.nodejs.yarn/yarn_modules/node_modules/opensea-js/lib/utils/utils.js:220:44
at step (/layers/google.nodejs.yarn/yarn_modules/node_modules/opensea-js/lib/utils/utils.js:63:23)
at Object.next (/layers/google.nodejs.yarn/yarn_modules/node_modules/opensea-js/lib/utils/utils.js:44:53)
at fulfilled (/layers/google.nodejs.yarn/yarn_modules/node_modules/opensea-js/lib/utils/utils.js:35:58)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This is displaying a console.warn within the following if case, but it continues processing, causing it to crash while trying to reference the status of the null receipt object.
https://github.com/ProjectOpenSea/opensea-js/blob/bf1954ad5360399633d44fa1fe76104e2fcda7fb/src/utils/utils.ts#L184-L189
I believe this is not a hack, but a bug due to a missing error handling. 
(To handle this properly, the poll process should be called again after waiting.)

For us OpenSea SDK users to handle this, we would have to globally monitor promise `unhandledRejection` , which is not realistic.

Please provide an appropriate fix.

Thank you.

**Comment by ryanio** [comment]
this has been refactored to use ethers in opensea-js v6, we will be releasing soon let us know if that fixes for you

**Comment by ryanio** [comment]
this should be fixed now, please open a new issue with details if you are still having trouble
