### ISSUE TITLE
API Error 400: Invalid protocol address.

### ISSUE THREAD

**Issue by creed-dev** [ProjectOpenSea/opensea-js#950]
From today I started getting an error when try to create sell order (there has never been such an error before and I could not find any information about it):

```
Error: API Error 400: Invalid protocol address. All orders must be for 0x00000000000000adc04c56bf30ac9d3c0aaf14dc
at OpenSeaAPI.<anonymous> (/home/ubuntu/aliens-nft/aliens-worker/node_modules/opensea-js/lib/api.js:583:31)
at step (/home/ubuntu/aliens-nft/aliens-worker/node_modules/opensea-js/lib/api.js:63:23)
at Object.next (/home/ubuntu/aliens-nft/aliens-worker/node_modules/opensea-js/lib/api.js:44:53)
at fulfilled (/home/ubuntu/aliens-nft/aliens-worker/node_modules/opensea-js/lib/api.js:35:58)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

package.json:

```
{
  "type": "commonjs",
  "scripts": {
    "start": "nodemon index.js"
  },
  "dependencies": {
    "@opensea/seaport-js": "^1.0.8",
    "@truffle/hdwallet-provider": "^2.1.8",
    "axios": "^0.27.2",
    "bull": "^4.10.3",
    "cors": "^2.8.5",
    "dotenv": "^16.0.2",
    "ethers": "^5.7.2",
    "express": "^4.18.2",
    "nodemon": "^2.0.22",
    "opensea-js": "^4.0.24",
    "web3": "^1.8.0",
    "winston": "^3.8.2",
    "wyvern-schemas": "^0.6.15"
  }
}
```

code:
```
require('dotenv').config();
const OpenSea = require("opensea-js");
const Network = require("opensea-js").Network;
const HDWalletProvider = require("@truffle/hdwallet-provider");
const {WyvernSchemaName} = require('opensea-js/lib/types');
const Web3 = require('web3');
const logger = require("./logger");

const {
    FIRST_STAFF_ADDRESS,
    FIRST_STAFF_ADDRESS_MNEMONIC,
    SECOND_STAFF_ADDRESS_MNEMONIC,
    NETWORK,
    INFURA_KEY,
    NFT_CONTRACT_ADDRESS,
    CHAIN_ID
} = process.env;

const OpenSeaSDK = OpenSea.OpenSeaSDK;

async function listing(tokenId, to, price) {
    try {
        logger.log('info', `Start listing function for token ID ${tokenId}`);

        const mnemonic = to === FIRST_STAFF_ADDRESS ? FIRST_STAFF_ADDRESS_MNEMONIC : SECOND_STAFF_ADDRESS_MNEMONIC;

        const provider = new HDWalletProvider({
            mnemonic: mnemonic,
            providerOrUrl: "https://" + NETWORK + ".infura.io/v3/" + INFURA_KEY,
            chainId: parseInt(CHAIN_ID)
        });

        const seaport = new OpenSeaSDK(
            provider,
            {
                networkName: Network.Goerli
            },
            (arg) => console.log(arg)
        );

        tokenId = tokenId.toString();
        const priceOnWei = price.toString();
        const priceOnEth = Number(Web3.utils.fromWei(priceOnWei, 'ether')).toFixed(10);

        logger.log('info', `Request to OpenSea API for token ID ${tokenId}`);

        const oldCreateOrder = seaport.seaport.createOrder;

        seaport.seaport.createOrder = async (input) => {
            const override = {
                restrictedByZone: false,
                allowPartialFills: false,
            };

            const newInput = {...input, ...override};

            return await oldCreateOrder.call(seaport.seaport, newInput);
        };

        await seaport.createSellOrder({
            asset: {
                tokenId: tokenId,
                tokenAddress: NFT_CONTRACT_ADDRESS,
                schemaName: WyvernSchemaName.ERC721
            },
            startAmount: priceOnEth,
            accountAddress: to
        });
    } catch (err) {
        throw err;
    }
}

module.exports = {listing};
```

**Comment by thenerdassassin** [comment]
You need to upgrade to version 5.0.0

**Comment by GarrisonXV** [comment]
> You need to upgrade to version 5.0.0

What do we need to do to upgrade to 5.0.0?

I tried just running npm update and it didn't fix it
